package goldcmds

// ============================================================================
// GOLD-MD — 500 MORE AI COMMANDS  (.ai system, batch 2)
// File: ai500.go
// ============================================================================
// Owner order (2026-09-19): 500 aur AI models add karo — bilkul wahi system
// jo ai200.go me hai. Har command ka apna guidance message, Mistral se jawab,
// brand identity prompt, aur .ai menu me category "AI" ke andar dikhe.
//
// NOTE: aiBrandsExtra ko ai200.go ke init() me register kiya jata hai
// (same loop, same Command struct) — is liye yahan koi init() nahi.
// ============================================================================

// aiBrandsExtra — 500 additional AI apps / models (batch 2).
var aiBrandsExtra = []aiBrand{
	{"gpt4o", "GPT-4o", "OpenAI", "OpenAI's fast multimodal flagship"},
	{"gpt4turbo", "GPT-4 Turbo", "OpenAI", "OpenAI's high-throughput model"},
	{"gpt4omini", "GPT-4o mini", "OpenAI", "OpenAI's small fast model"},
	{"gpt41", "GPT-4.1", "OpenAI", "OpenAI's coding-strong model"},
	{"gpt41mini", "GPT-4.1 mini", "OpenAI", "OpenAI's compact 4.1 model"},
	{"gpt41nano", "GPT-4.1 nano", "OpenAI", "OpenAI's fastest small model"},
	{"gpt45", "GPT-4.5", "OpenAI", "OpenAI's largest GPT model"},
	{"gpt5mini", "GPT-5 mini", "OpenAI", "OpenAI's efficient GPT-5"},
	{"gpt5nano", "GPT-5 nano", "OpenAI", "OpenAI's lightweight GPT-5"},
	{"o1mini", "o1-mini", "OpenAI", "OpenAI's compact reasoning model"},
	{"o1preview", "o1-preview", "OpenAI", "OpenAI's first reasoning preview"},
	{"o3mini", "o3-mini", "OpenAI", "OpenAI's fast reasoning model"},
	{"o4mini", "o4-mini", "OpenAI", "OpenAI's efficient reasoning model"},
	{"chatgpt4o", "ChatGPT-4o", "OpenAI", "ChatGPT powered by GPT-4o"},
	{"chatgpt5", "ChatGPT-5", "OpenAI", "ChatGPT powered by GPT-5"},
	{"claude35", "Claude 3.5", "Anthropic", "Anthropic's balanced 3.5 model"},
	{"claude37", "Claude 3.7", "Anthropic", "Anthropic's hybrid reasoning model"},
	{"claude4", "Claude 4", "Anthropic", "Anthropic's newest model family"},
	{"claudeopus4", "Claude Opus 4", "Anthropic", "Anthropic's most powerful model"},
	{"claudesonnet4", "Claude Sonnet 4", "Anthropic", "Anthropic's balanced flagship"},
	{"claudehaiku4", "Claude Haiku 4", "Anthropic", "Anthropic's fastest model"},
	{"gemini15", "Gemini 1.5", "Google", "Google's long-context model"},
	{"gemini20", "Gemini 2.0", "Google", "Google's agentic model"},
	{"gemini25", "Gemini 2.5", "Google", "Google's thinking model"},
	{"gemini25pro", "Gemini 2.5 Pro", "Google", "Google's advanced reasoning model"},
	{"gemini25flash", "Gemini 2.5 Flash", "Google", "Google's fast thinking model"},
	{"gemini2flash", "Gemini 2.0 Flash", "Google", "Google's fast multimodal model"},
	{"llama2", "Llama 2", "Meta", "Meta's open chat model"},
	{"llama3", "Llama 3", "Meta", "Meta's open flagship"},
	{"llama31", "Llama 3.1", "Meta", "Meta's 405B open model"},
	{"llama32", "Llama 3.2", "Meta", "Meta's small vision models"},
	{"llama33", "Llama 3.3", "Meta", "Meta's efficient 70B model"},
	{"llama4", "Llama 4", "Meta", "Meta's natively multimodal model"},
	{"llamaguard", "Llama Guard", "Meta", "Meta's safety classifier"},
	{"codellama", "Code Llama", "Meta", "Meta's code model"},
	{"qwen2", "Qwen 2", "Alibaba", "Alibaba's open model"},
	{"qwen25", "Qwen 2.5", "Alibaba", "Alibaba's strong open model"},
	{"qwen3", "Qwen 3", "Alibaba", "Alibaba's hybrid reasoning model"},
	{"qwencoder", "Qwen Coder", "Alibaba", "Alibaba's code model"},
	{"qwenvl", "Qwen VL", "Alibaba", "Alibaba's vision-language model"},
	{"qwenmax", "Qwen Max", "Alibaba", "Alibaba's largest model"},
	{"deepseekv2", "DeepSeek V2", "DeepSeek", "DeepSeek's MoE model"},
	{"deepseekv3", "DeepSeek V3", "DeepSeek", "DeepSeek's flagship MoE"},
	{"deepseekr1", "DeepSeek R1", "DeepSeek", "DeepSeek's reasoning model"},
	{"deepseekcoder", "DeepSeek Coder", "DeepSeek", "DeepSeek's code model"},
	{"deepseekvl", "DeepSeek VL", "DeepSeek", "DeepSeek's vision model"},
	{"mistral7b", "Mistral 7B", "Mistral AI", "Mistral's compact model"},
	{"mixtral", "Mixtral", "Mistral AI", "Mistral's mixture-of-experts"},
	{"mistralnemo", "Mistral NeMo", "Mistral AI", "Mistral's Nvidia model"},
	{"mistralsmall", "Mistral Small", "Mistral AI", "Mistral's efficient model"},
	{"mistrallarge", "Mistral Large", "Mistral AI", "Mistral's flagship model"},
	{"codestral", "Codestral", "Mistral AI", "Mistral's code model"},
	{"pixtral", "Pixtral", "Mistral AI", "Mistral's vision model"},
	{"voxtral", "Voxtral", "Mistral AI", "Mistral's audio model"},
	{"devstral", "Devstral", "Mistral AI", "Mistral's coding agent model"},
	{"magistral", "Magistral", "Mistral AI", "Mistral's reasoning model"},
	{"phi3", "Phi-3", "Microsoft", "Microsoft's small model"},
	{"phi4", "Phi-4", "Microsoft", "Microsoft's reasoning small model"},
	{"phi35", "Phi-3.5", "Microsoft", "Microsoft's multimodal small model"},
	{"gemma2", "Gemma 2", "Google", "Google's open model"},
	{"gemma3", "Gemma 3", "Google", "Google's multimodal open model"},
	{"gemmacode", "CodeGemma", "Google", "Google's code model"},
	{"paligemma", "PaliGemma", "Google", "Google's vision-language model"},
	{"recurrentgemma", "RecurrentGemma", "Google", "Google's efficient model"},
	{"shieldgemma", "ShieldGemma", "Google", "Google's safety model"},
	{"commandr", "Command R", "Cohere", "Cohere's scalable model"},
	{"commandrplus", "Command R+", "Cohere", "Cohere's flagship model"},
	{"commandlight", "Command Light", "Cohere", "Cohere's fast model"},
	{"aya", "Aya", "Cohere", "Cohere's multilingual model"},
	{"jamba15", "Jamba 1.5", "AI21", "AI21's hybrid SSM model"},
	{"jurassic2", "Jurassic-2", "AI21", "AI21's language model"},
	{"olmo", "OLMo", "Allen Institute", "Allen's open model"},
	{"molmo", "Molmo", "Allen Institute", "Allen's multimodal model"},
	{"tulu", "Tulu", "Allen Institute", "Allen's instruction model"},
	{"falcon2", "Falcon 2", "TII", "TII's open model"},
	{"falcong", "Falcon 180B", "TII", "TII's large open model"},
	{"vicuna13", "Vicuna 13B", "LMSYS", "LMSYS's chat model"},
	{"openhermes", "OpenHermes", "Nous Research", "Nous's fine-tuned model"},
	{"hermes3", "Hermes 3", "Nous Research", "Nous's frontier model"},
	{"nousresearch", "Nous Research", "Nous Research", "Open research AI"},
	{"dolphin", "Dolphin", "Cognitive Computations", "Uncensored fine-tune"},
	{"zephyr7b", "Zephyr 7B", "Hugging Face", "Hugging Face's chat model"},
	{"smollm", "SmolLM", "Hugging Face", "Hugging Face's tiny model"},
	{"starcoder", "StarCoder", "BigCode", "BigCode's code model"},
	{"santacoder", "SantaCoder", "BigCode", "BigCode's small code model"},
	{"bloomz", "BLOOMZ", "BigScience", "BigScience's multilingual model"},
	{"mpt7b", "MPT-7B", "MosaicML", "MosaicML's open model"},
	{"dbrx", "DBRX", "Databricks", "Databricks' MoE model"},
	{"dolly2", "Dolly 2.0", "Databricks", "Databricks' instruction model"},
	{"redpajama2", "RedPajama", "Together", "Together's open model"},
	{"stripedhyena", "StripedHyena", "Together", "Together's efficient model"},
	{"arctic", "Arctic", "Snowflake", "Snowflake's enterprise model"},
	{"snowflakeai", "Snowflake AI", "Snowflake", "Snowflake's data AI"},
	{"granite", "Granite", "IBM", "IBM's enterprise model"},
	{"granitecode", "Granite Code", "IBM", "IBM's code model"},
	{"nemotron", "Nemotron", "Nvidia", "Nvidia's open model"},
	{"nemotron4", "Nemotron-4", "Nvidia", "Nvidia's synthetic data model"},
	{"chatqa", "ChatQA", "Nvidia", "Nvidia's QA model"},
	{"riva", "Riva", "Nvidia", "Nvidia's speech AI"},
	{"parakeet", "Parakeet", "Nvidia", "Nvidia's ASR model"},
	{"canary", "Canary", "Nvidia", "Nvidia's speech model"},
	{"olmo2", "OLMo 2", "Allen Institute", "Allen's improved open model"},
	{"exaone3", "EXAONE 3", "LG", "LG's open model"},
	{"solar10", "SOLAR 10.7B", "Upstage", "Upstage's open model"},
	{"hyperclovax", "HyperCLOVA X", "Naver", "Naver's Korean model"},
	{"kogpt2", "KoGPT", "Kakao", "Kakao's Korean model"},
	{"yi34", "Yi 34B", "01.AI", "01.AI's large open model"},
	{"internlm2", "InternLM 2", "Shanghai AI Lab", "Shanghai's open model"},
	{"internvl", "InternVL", "Shanghai AI Lab", "Shanghai's vision model"},
	{"minicpm", "MiniCPM", "OpenBMB", "OpenBMB's small model"},
	{"cpmbee", "CPM-Bee", "OpenBMB", "OpenBMB's bilingual model"},
	{"baichuan2", "Baichuan 2", "Baichuan", "Baichuan's open model"},
	{"chatglm4", "ChatGLM 4", "Zhipu AI", "Zhipu's open model"},
	{"glm4", "GLM-4", "Zhipu AI", "Zhipu's flagship model"},
	{"cogvlm", "CogVLM", "Zhipu AI", "Zhipu's vision model"},
	{"ernie4", "ERNIE 4.0", "Baidu", "Baidu's flagship model"},
	{"erniespeed", "ERNIE Speed", "Baidu", "Baidu's fast model"},
	{"wenxin4", "Wenxin 4.0", "Baidu", "Baidu's knowledge model"},
	{"doubao1", "Doubao 1.5", "ByteDance", "ByteDance's flagship model"},
	{"skylark", "Skylark", "ByteDance", "ByteDance's model"},
	{"seed", "Seed", "ByteDance", "ByteDance's research model"},
	{"hunyuanpro", "Hunyuan Pro", "Tencent", "Tencent's flagship model"},
	{"hunyuanlarge", "Hunyuan Large", "Tencent", "Tencent's large model"},
	{"yuanbao", "Yuanbao", "Tencent", "Tencent's AI assistant"},
	{"spark4", "Spark 4.0", "iFlytek", "iFlytek's cognitive model"},
	{"step2", "Step-2", "StepFun", "StepFun's MoE model"},
	{"step1x", "Step-1X", "StepFun", "StepFun's image model"},
	{"minimax01", "MiniMax-01", "MiniMax", "MiniMax's long-context model"},
	{"abab7", "ABAB 7", "MiniMax", "MiniMax's large model"},
	{"hailuoai", "Hailuo AI", "MiniMax", "MiniMax's video AI"},
	{"kimi2", "Kimi k2", "Moonshot AI", "Moonshot's agentic model"},
	{"moonshotv1", "Moonshot v1", "Moonshot AI", "Moonshot's long-context model"},
	{"skywork2", "Skywork 2", "Kunlun", "Kunlun's model"},
	{"tiangong4", "Tiangong 4.0", "Kunlun", "Kunlun's chatbot"},
	{"sensetime", "SenseNova", "SenseTime", "SenseTime's multimodal AI"},
	{"sensechat5", "SenseChat 5", "SenseTime", "SenseTime's chat model"},
	{"baichuan4", "Baichuan 4", "Baichuan", "Baichuan's flagship"},
	{"lingyi", "Lingyi", "01.AI", "01.AI's model"},
	{"wanzhi", "Wanzhi", "01.AI", "01.AI's enterprise AI"},
	{"hunyuanvideo", "HunyuanVideo", "Tencent", "Tencent's video model"},
	{"kolors", "Kolors", "Kuaishou", "Kuaishou's image model"},
	{"kling2", "Kling 2.0", "Kuaishou", "Kuaishou's video model"},
	{"vidu", "Vidu", "Shengshu", "Shengshu's video model"},
	{"pixverse", "PixVerse", "AIsphere", "AIsphere's video model"},
	{"hailuo2", "Hailuo 02", "MiniMax", "MiniMax's video model"},
	{"seedance", "Seedance", "ByteDance", "ByteDance's video model"},
	{"seedream", "Seedream", "ByteDance", "ByteDance's image model"},
	{"jimeng", "Jimeng", "ByteDance", "ByteDance's creative AI"},
	{"doubaovideo", "Doubao Video", "ByteDance", "ByteDance's video AI"},
	{"wanx", "Wanx", "Alibaba", "Alibaba's image model"},
	{"tongyi", "Tongyi", "Alibaba", "Alibaba's AI assistant"},
	{"tongyiwanxiang", "Tongyi Wanxiang", "Alibaba", "Alibaba's image AI"},
	{"qwenimage", "Qwen Image", "Alibaba", "Alibaba's image model"},
	{"qwenvideo", "Qwen Video", "Alibaba", "Alibaba's video model"},
	{"qwenaudio", "Qwen Audio", "Alibaba", "Alibaba's audio model"},
	{"qwenomni", "Qwen Omni", "Alibaba", "Alibaba's omni model"},
	{"qwenmath", "Qwen Math", "Alibaba", "Alibaba's math model"},
	{"qwencode", "Qwen Code", "Alibaba", "Alibaba's coding model"},
	{"qwenlong", "Qwen Long", "Alibaba", "Alibaba's long-context model"},
	{"qwenmax2", "Qwen Max 2", "Alibaba", "Alibaba's newest flagship"},
	{"codeium2", "Codeium", "Codeium", "Free AI coding assistant"},
	{"tabnine2", "Tabnine", "Tabnine", "AI code completion"},
	{"codota", "Codota", "Codota", "AI code completion"},
	{"kite", "Kite", "Kite", "AI code completion"},
	{"sourcery", "Sourcery", "Sourcery", "AI code review"},
	{"codiga", "Codiga", "Codiga", "AI code analysis"},
	{"deepcode", "DeepCode", "Snyk", "AI code review"},
	{"snykcode", "Snyk Code", "Snyk", "AI security scanning"},
	{"mutableai", "MutableAI", "Mutable", "AI code refactoring"},
	{"codeguru", "CodeGuru", "AWS", "AWS AI code review"},
	{"duetai", "Duet AI", "Google", "Google's AI coding"},
	{"geminicodeassist", "Gemini Code Assist", "Google", "Google's coding assistant"},
	{"firebaseai", "Firebase AI", "Google", "Google's app AI"},
	{"copilotx", "Copilot X", "GitHub", "GitHub's AI coding"},
	{"copilotcli", "Copilot CLI", "GitHub", "GitHub's terminal AI"},
	{"codespacesai", "Codespaces AI", "GitHub", "GitHub's cloud AI"},
	{"gitpodai", "Gitpod AI", "Gitpod", "Gitpod's AI dev"},
	{"codeanywhere", "Codeanywhere", "Codeanywhere", "Cloud AI IDE"},
	{"replitghostwriter", "Ghostwriter", "Replit", "Replit's AI coder"},
	{"stackblitz", "StackBlitz", "StackBlitz", "Browser AI IDE"},
	{"codesandbox", "CodeSandbox", "CodeSandbox", "Cloud AI IDE"},
	{"glitch", "Glitch", "Glitch", "AI app builder"},
	{"valtown", "Val Town", "Val Town", "AI code snippets"},
	{"marblism", "Marblism", "Marblism", "AI app generator"},
	{"a0dev", "a0.dev", "a0", "AI mobile app builder"},
	{"softgen", "Softgen", "Softgen", "AI web app builder"},
	{"databutton", "Databutton", "Databutton", "AI app builder"},
	{"createxyz", "Create.xyz", "Create", "AI app builder"},
	{"tempo", "Tempo", "Tempo", "AI app builder"},
	{"builderio", "Builder.io", "Builder.io", "AI visual dev"},
	{"locofy", "Locofy", "Locofy", "Design to code AI"},
	{"anima", "Anima", "Anima", "Design to code AI"},
	{"teleporthq", "TeleportHQ", "TeleportHQ", "Design to code AI"},
	{"quest", "Quest", "Quest", "AI app builder"},
	{"aider2", "Aider", "Aider", "AI pair programming"},
	{"gptengineer", "GPT Engineer", "Open Source", "AI code generator"},
	{"gptpilot", "GPT Pilot", "Open Source", "AI app developer"},
	{"smoldev", "smol developer", "Open Source", "AI code agent"},
	{"mentat", "Mentat", "Open Source", "AI coding agent"},
	{"openinterpreter", "Open Interpreter", "Open Source", "AI code runner"},
	{"opendevin", "OpenDevin", "Open Source", "AI software engineer"},
	{"devika", "Devika", "Open Source", "AI software engineer"},
	{"gptswarm", "GPT-Swarm", "Open Source", "AI dev swarm"},
	{"sweepai", "Sweep", "Sweep", "AI GitHub assistant"},
	{"codegen2", "CodeGen", "Salesforce", "Salesforce code model"},
	{"codex2", "Codex", "OpenAI", "OpenAI's code model"},
	{"codexmini", "Codex mini", "OpenAI", "OpenAI's fast code model"},
	{"codexcli", "Codex CLI", "OpenAI", "OpenAI's terminal coder"},
	{"claudecode2", "Claude Code", "Anthropic", "Anthropic's terminal coder"},
	{"geminicli2", "Gemini CLI", "Google", "Google's terminal AI"},
	{"qwencli", "Qwen Code CLI", "Alibaba", "Alibaba's terminal coder"},
	{"opencode2", "OpenCode", "OpenCode", "Open terminal AI coder"},
	{"crush", "Crush", "Charm", "Terminal AI coder"},
	{"amp", "Amp", "Sourcegraph", "Agentic coding tool"},
	{"windsurf2", "Windsurf", "Codeium", "Agentic IDE"},
	{"cursor2", "Cursor", "Anysphere", "AI-first code editor"},
	{"zed2", "Zed", "Zed", "High-performance AI editor"},
	{"void2", "Void", "Void", "Open AI editor"},
	{"pearai2", "PearAI", "PearAI", "Open AI editor"},
	{"continue2", "Continue", "Continue", "Open AI assistant"},
	{"cline2", "Cline", "Cline", "Autonomous coding agent"},
	{"roocode", "Roo Code", "Roo", "AI coding agent"},
	{"kilo", "Kilo Code", "Kilo", "AI coding agent"},
	{"trae", "Trae", "ByteDance", "AI IDE"},
	{"lingma", "Lingma", "Alibaba", "Alibaba's coding assistant"},
	{"comate", "Comate", "Baidu", "Baidu's coding assistant"},
	{"codebuddy", "CodeBuddy", "Tencent", "Tencent's coding AI"},
	{"iflycode", "iFlyCode", "iFlytek", "iFlytek's coding AI"},
	{"codegeex", "CodeGeeX", "Zhipu AI", "Zhipu's code model"},
	{"codefuse", "CodeFuse", "Ant Group", "Ant's code AI"},
	{"cosmos", "Cosmos", "Open Source", "AI code assistant"},
	{"refact", "Refact", "Refact", "Open AI coding"},
	{"twinny", "Twinny", "Open Source", "Local AI coding"},
	{"fitten", "Fitten Code", "Fitten", "AI coding assistant"},
	{"blackbox2", "Blackbox AI", "Blackbox", "AI coding assistant"},
	{"askcodi2", "AskCodi", "AskCodi", "AI coding assistant"},
	{"codeiumchat", "Codeium Chat", "Codeium", "AI coding chat"},
	{"phind2", "Phind", "Phind", "AI for developers"},
	{"youcode", "YouCode", "You.com", "AI coding search"},
	{"perplexitycode", "Perplexity Code", "Perplexity", "AI coding search"},
	{"sourcegraph2", "Sourcegraph", "Sourcegraph", "Code intelligence AI"},
	{"cody2", "Cody", "Sourcegraph", "AI coding assistant"},
	{"greptile", "Greptile", "Greptile", "AI code review"},
	{"coderabbit", "CodeRabbit", "CodeRabbit", "AI code review"},
	{"ellipsis", "Ellipsis", "Ellipsis", "AI code review"},
	{"graphite", "Graphite", "Graphite", "AI code review"},
	{"qodo2", "Qodo", "Qodo", "AI code integrity"},
	{"codium2", "Codium", "Codium", "AI code coverage"},
	{"diffblue", "Diffblue", "Diffblue", "AI test generation"},
	{"meticulous", "Meticulous", "Meticulous", "AI test generation"},
	{"testim", "Testim", "Tricentis", "AI test automation"},
	{"mabl", "mabl", "mabl", "AI test automation"},
	{"applitools", "Applitools", "Applitools", "AI visual testing"},
	{"functionize", "Functionize", "Functionize", "AI testing"},
	{"reload", "Reload", "Reload", "AI code collaboration"},
	{"midjourney2", "Midjourney v6", "Midjourney", "Midjourney's newest model"},
	{"dalle3", "DALL·E 3", "OpenAI", "OpenAI's image model"},
	{"gptimage", "GPT Image", "OpenAI", "OpenAI's image generator"},
	{"sora2", "Sora", "OpenAI", "OpenAI's video model"},
	{"firefly2", "Firefly", "Adobe", "Adobe's image AI"},
	{"fireflyvideo", "Firefly Video", "Adobe", "Adobe's video AI"},
	{"photoshopai", "Photoshop AI", "Adobe", "Adobe's photo AI"},
	{"illustratorai", "Illustrator AI", "Adobe", "Adobe's vector AI"},
	{"expressai", "Express AI", "Adobe", "Adobe's design AI"},
	{"lightroomai", "Lightroom AI", "Adobe", "Adobe's photo AI"},
	{"premiereai", "Premiere AI", "Adobe", "Adobe's video AI"},
	{"aftereffectsai", "After Effects AI", "Adobe", "Adobe's motion AI"},
	{"auditionai", "Audition AI", "Adobe", "Adobe's audio AI"},
	{"substanceai", "Substance AI", "Adobe", "Adobe's 3D AI"},
	{"stable2", "Stable Diffusion 3", "Stability AI", "Stability's image model"},
	{"sdxl2", "SDXL Turbo", "Stability AI", "Stability's fast model"},
	{"stablevideo", "Stable Video", "Stability AI", "Stability's video model"},
	{"stableaudio", "Stable Audio", "Stability AI", "Stability's audio model"},
	{"stablecode", "Stable Code", "Stability AI", "Stability's code model"},
	{"stabilityapi", "Stability API", "Stability AI", "Stability's API"},
	{"dreamstudio2", "DreamStudio", "Stability AI", "Stability's studio"},
	{"clipdrop2", "Clipdrop", "Stability AI", "Stability's editing suite"},
	{"leonardo2", "Leonardo AI", "Leonardo", "Leonardo's image AI"},
	{"leonardovideo", "Leonardo Motion", "Leonardo", "Leonardo's video AI"},
	{"ideogram2", "Ideogram", "Ideogram", "Ideogram's text image AI"},
	{"flux2", "FLUX.1", "Black Forest Labs", "Black Forest's image model"},
	{"fluxpro", "FLUX Pro", "Black Forest Labs", "Black Forest's pro model"},
	{"fluxdev", "FLUX Dev", "Black Forest Labs", "Black Forest's dev model"},
	{"recraft", "Recraft", "Recraft", "AI vector design"},
	{"krea", "Krea", "Krea", "Real-time AI image"},
	{"playground2", "Playground", "Playground AI", "Playground's image AI"},
	{"nightcafe2", "NightCafe", "NightCafe", "AI art community"},
	{"wombo", "Wombo", "Wombo", "AI art app"},
	{"dream", "Dream", "Wombo", "AI art generator"},
	{"starryai2", "StarryAI", "StarryAI", "AI art app"},
	{"picsart", "Picsart AI", "Picsart", "AI photo editing"},
	{"canva2", "Canva AI", "Canva", "Canva's design AI"},
	{"magicstudio", "Magic Studio", "Canva", "Canva's AI suite"},
	{"adobefirefly", "Adobe Firefly", "Adobe", "Adobe's generative AI"},
	{"microsoftdesigner", "Designer", "Microsoft", "Microsoft's design AI"},
	{"bingimagecreator", "Image Creator", "Microsoft", "Microsoft's image AI"},
	{"copilotdesigner", "Copilot Designer", "Microsoft", "Microsoft's design AI"},
	{"metaaiimage", "Meta AI Image", "Meta", "Meta's image AI"},
	{"imagine", "Imagine", "Meta", "Meta's image generator"},
	{"grokimage", "Grok Image", "xAI", "xAI's image model"},
	{"aurora", "Aurora", "xAI", "xAI's image model"},
	{"geminiimage", "Gemini Image", "Google", "Google's image model"},
	{"imagen", "Imagen", "Google", "Google's image model"},
	{"imagen3", "Imagen 3", "Google", "Google's newest image model"},
	{"veo2", "Veo 2", "Google", "Google's video model"},
	{"veo3", "Veo 3", "Google", "Google's video+audio model"},
	{"whisk", "Whisk", "Google", "Google's image remix tool"},
	{"flow", "Flow", "Google", "Google's AI filmmaking tool"},
	{"lumiere", "Lumiere", "Google", "Google's video model"},
	{"phenaki", "Phenaki", "Google", "Google's video model"},
	{"parti", "Parti", "Google", "Google's image model"},
	{"muse", "Muse", "Google", "Google's image model"},
	{"runway3", "Runway Gen-3", "Runway", "Runway's video model"},
	{"runway4", "Runway Gen-4", "Runway", "Runway's newest video model"},
	{"pika2", "Pika 2.0", "Pika", "Pika's video model"},
	{"luma2", "Dream Machine", "Luma AI", "Luma's video model"},
	{"ray2", "Ray2", "Luma AI", "Luma's video model"},
	{"kling3", "Kling 1.6", "Kuaishou", "Kuaishou's video model"},
	{"hailuo3", "Hailuo", "MiniMax", "MiniMax's video model"},
	{"genmo2", "Mochi", "Genmo", "Genmo's video model"},
	{"haiper2", "Haiper", "Haiper", "Haiper's video model"},
	{"kaiber2", "Kaiber", "Kaiber", "AI music video"},
	{"deforum2", "Deforum", "Open Source", "AI animation"},
	{"animatediff", "AnimateDiff", "Open Source", "AI animation"},
	{"svd", "Stable Video Diffusion", "Stability AI", "Stability's video model"},
	{"cogvideo", "CogVideo", "Zhipu AI", "Zhipu's video model"},
	{"opensora", "Open-Sora", "Open Source", "Open video model"},
	{"mochi1", "Mochi 1", "Genmo", "Genmo's open video model"},
	{"ltx", "LTX Video", "Lightricks", "Lightricks' video model"},
	{"lightricks", "Lightricks", "Lightricks", "AI creative tools"},
	{"pixverse2", "PixVerse", "AIsphere", "AIsphere's video model"},
	{"vidu2", "Vidu", "Shengshu", "Shengshu's video model"},
	{"dreamina", "Dreamina", "ByteDance", "ByteDance's creative AI"},
	{"jimeng2", "Jimeng AI", "ByteDance", "ByteDance's image AI"},
	{"seedream2", "Seedream", "ByteDance", "ByteDance's image model"},
	{"seededit", "SeedEdit", "ByteDance", "ByteDance's image editor"},
	{"seedance2", "Seedance", "ByteDance", "ByteDance's video model"},
	{"wan", "Wan", "Alibaba", "Alibaba's video model"},
	{"wan21", "Wan 2.1", "Alibaba", "Alibaba's open video model"},
	{"hunyuanimage", "HunyuanImage", "Tencent", "Tencent's image model"},
	{"hunyuan3d", "Hunyuan3D", "Tencent", "Tencent's 3D model"},
	{"hunyuanportrait", "HunyuanPortrait", "Tencent", "Tencent's portrait AI"},
	{"kolors2", "Kolors", "Kuaishou", "Kuaishou's image model"},
	{"step1xedit", "Step1X-Edit", "StepFun", "StepFun's image editor"},
	{"stepvideo", "Step-Video", "StepFun", "StepFun's video model"},
	{"skyreels", "SkyReels", "Kunlun", "Kunlun's video model"},
	{"vidu3", "Vidu Q1", "Shengshu", "Shengshu's video model"},
	{"pixart", "PixArt", "Open Source", "Open image model"},
	{"sd3", "Stable Diffusion 3", "Stability AI", "Stability's image model"},
	{"sd35", "SD 3.5", "Stability AI", "Stability's newest image model"},
	{"sdxl3", "SDXL", "Stability AI", "Stability's high-res model"},
	{"kandinsky", "Kandinsky", "Sber", "Sber's image model"},
	{"deepfloyd", "DeepFloyd IF", "Stability AI", "Text-to-image model"},
	{"wuerstchen", "Würstchen", "Open Source", "Efficient image model"},
	{"playgroundv2", "Playground v2", "Playground AI", "Playground's model"},
	{"amused", "Amused", "Open Source", "Fast image model"},
	{"pixartsigma", "PixArt-Sigma", "Open Source", "Open image model"},
	{"lumina", "Lumina", "Open Source", "Open image model"},
	{"hunyuandit", "Hunyuan-DiT", "Tencent", "Tencent's DiT model"},
	{"cogview", "CogView", "Zhipu AI", "Zhipu's image model"},
	{"ernieimage", "ERNIE Image", "Baidu", "Baidu's image model"},
	{"wenxinimage", "Wenxin Image", "Baidu", "Baidu's image AI"},
	{"doubaoimage", "Doubao Image", "ByteDance", "ByteDance's image AI"},
	{"tongyiimage", "Tongyi Image", "Alibaba", "Alibaba's image AI"},
	{"baiduimage", "Baidu Image", "Baidu", "Baidu's image AI"},
	{"elevenlabs2", "ElevenLabs", "ElevenLabs", "ElevenLabs' voice AI"},
	{"elevenmultilingual", "Eleven Multilingual", "ElevenLabs", "ElevenLabs' multilingual"},
	{"elevenflash", "Eleven Flash", "ElevenLabs", "ElevenLabs' fast model"},
	{"elevenreader", "ElevenReader", "ElevenLabs", "ElevenLabs' reader"},
	{"elevenmusic", "Eleven Music", "ElevenLabs", "ElevenLabs' music AI"},
	{"elevenagents", "Eleven Agents", "ElevenLabs", "ElevenLabs' voice agents"},
	{"playai", "PlayAI", "PlayAI", "PlayAI's voice AI"},
	{"playht2", "PlayHT", "PlayHT", "PlayHT's voice AI"},
	{"murf2", "Murf", "Murf", "Murf's voice AI"},
	{"speechify2", "Speechify", "Speechify", "Speechify's reading AI"},
	{"resemble2", "Resemble AI", "Resemble", "Resemble's voice cloning"},
	{"resembledetect", "Resemble Detect", "Resemble", "Deepfake detection"},
	{"descript2", "Descript", "Descript", "Descript's audio editing"},
	{"descriptoverdub", "Overdub", "Descript", "Descript's voice cloning"},
	{"adobeenhance", "Enhance Speech", "Adobe", "Adobe's speech AI"},
	{"podcastle", "Podcastle", "Podcastle", "AI podcasting"},
	{"auphonic", "Auphonic", "Auphonic", "AI audio post"},
	{"cleanvoice", "CleanVoice", "CleanVoice", "AI audio cleanup"},
	{"krisp2", "Krisp", "Krisp", "AI noise cancellation"},
	{"nvidiabroadcast", "NVIDIA Broadcast", "Nvidia", "AI broadcast audio"},
	{"voicemod2", "Voicemod", "Voicemod", "AI voice changer"},
	{"voicemodai", "Voicemod AI", "Voicemod", "AI voice effects"},
	{"lalal", "LALAL.AI", "LALAL.AI", "AI stem separation"},
	{"moises", "Moises", "Moises", "AI music practice"},
	{"suno2", "Suno", "Suno", "Suno's music AI"},
	{"suno3", "Suno v3", "Suno", "Suno's music model"},
	{"suno4", "Suno v4", "Suno", "Suno's newest music model"},
	{"udio2", "Udio", "Udio", "Udio's music AI"},
	{"riffusion2", "Riffusion", "Riffusion", "Riffusion's music AI"},
	{"stableaudio2", "Stable Audio", "Stability AI", "Stability's audio model"},
	{"musicgen", "MusicGen", "Meta", "Meta's music model"},
	{"audiocraft", "AudioCraft", "Meta", "Meta's audio suite"},
	{"audiogen", "AudioGen", "Meta", "Meta's sound model"},
	{"musiclm", "MusicLM", "Google", "Google's music model"},
	{"musicfx", "MusicFX", "Google", "Google's music AI"},
	{"lyria", "Lyria", "Google", "Google's music model"},
	{"magenta", "Magenta", "Google", "Google's music AI"},
	{"aiva2", "AIVA", "AIVA", "AIVA's music composer"},
	{"soundraw2", "Soundraw", "Soundraw", "Soundraw's music AI"},
	{"boomy2", "Boomy", "Boomy", "Boomy's music AI"},
	{"beatoven2", "Beatoven.ai", "Beatoven", "Beatoven's music AI"},
	{"mubert2", "Mubert", "Mubert", "Mubert's music AI"},
	{"soundful2", "Soundful", "Soundful", "Soundful's music AI"},
	{"loudly2", "Loudly", "Loudly", "Loudly's music AI"},
	{"splash2", "Splash", "Splash", "Splash's music AI"},
	{"epidemicsound", "Epidemic Sound", "Epidemic Sound", "AI music library"},
	{"soundverse", "Soundverse", "Soundverse", "AI music assistant"},
	{"sonauto", "Sonauto", "Sonauto", "AI song generator"},
	{"acestep", "ACE-Step", "Open Source", "Open music model"},
	{"yue", "YuE", "Open Source", "Open music model"},
	{"musicgen2", "MusicGen", "Meta", "Meta's open music model"},
	{"bark", "Bark", "Suno", "Suno's open audio model"},
	{"tortoise", "Tortoise TTS", "Open Source", "Open TTS model"},
	{"coqui", "Coqui TTS", "Coqui", "Open TTS"},
	{"piper", "Piper", "Open Source", "Fast TTS"},
	{"xtts", "XTTS", "Coqui", "Voice cloning TTS"},
	{"openvoice", "OpenVoice", "MyShell", "Voice cloning TTS"},
	{"myshell", "MyShell", "MyShell", "AI voice platform"},
	{"fishaudio", "Fish Audio", "Fish Audio", "AI voice cloning"},
	{"fishspeech", "Fish Speech", "Fish Audio", "Open TTS model"},
	{"f5tts", "F5-TTS", "Open Source", "Open TTS model"},
	{"styletts", "StyleTTS", "Open Source", "Expressive TTS"},
	{"kokoro", "Kokoro", "Open Source", "Lightweight TTS"},
	{"sherpa", "Sherpa", "Open Source", "On-device TTS"},
	{"whisper2", "Whisper", "OpenAI", "OpenAI's speech model"},
	{"whisperlarge", "Whisper Large", "OpenAI", "OpenAI's large ASR"},
	{"whisperx", "WhisperX", "Open Source", "Fast ASR alignment"},
	{"fasterwhisper", "Faster Whisper", "Open Source", "Fast ASR engine"},
	{"insanelyfast", "Insanely Fast Whisper", "Open Source", "Fast ASR"},
	{"distilwhisper", "Distil-Whisper", "Hugging Face", "Distilled ASR"},
	{"nemo", "NeMo", "Nvidia", "Nvidia's speech toolkit"},
	{"deepgram2", "Deepgram", "Deepgram", "Deepgram's speech AI"},
	{"assemblyai2", "AssemblyAI", "AssemblyAI", "AssemblyAI's speech AI"},
	{"revai2", "Rev AI", "Rev", "Rev's speech AI"},
	{"speechmatics", "Speechmatics", "Speechmatics", "Accurate speech AI"},
	{"sonix2", "Sonix", "Sonix", "AI transcription"},
	{"otter2", "Otter", "Otter.ai", "AI meeting notes"},
	{"fireflies2", "Fireflies", "Fireflies", "AI meeting assistant"},
	{"fathom2", "Fathom", "Fathom", "AI meeting recorder"},
	{"tldv2", "tl;dv", "tl;dv", "AI meeting recorder"},
	{"grain2", "Grain", "Grain", "AI meeting notes"},
	{"avoma2", "Avoma", "Avoma", "AI meeting assistant"},
	{"supernormal2", "Supernormal", "Supernormal", "AI meeting notes"},
	{"jamie2", "Jamie", "Jamie", "AI meeting notes"},
	{"notta2", "Notta", "Notta", "AI transcription"},
	{"trint2", "Trint", "Trint", "AI transcription"},
	{"happyscribe", "Happy Scribe", "Happy Scribe", "AI transcription"},
	{"sonixai", "Sonix AI", "Sonix", "AI transcription"},
	{"veed2", "VEED", "VEED", "AI video editing"},
	{"kapwing2", "Kapwing", "Kapwing", "AI video editing"},
	{"pictory2", "Pictory", "Pictory", "AI video editing"},
	{"fliki2", "Fliki", "Fliki", "AI video creation"},
	{"lumen5b", "Lumen5", "Lumen5", "AI video creation"},
	{"invideo2", "InVideo", "InVideo", "AI video creation"},
	{"synthesia2", "Synthesia", "Synthesia", "AI video avatars"},
	{"heygen2", "HeyGen", "HeyGen", "AI video avatars"},
	{"did2", "D-ID", "D-ID", "AI video avatars"},
	{"elai2", "Elai.io", "Elai", "AI video avatars"},
	{"colossyan2", "Colossyan", "Colossyan", "AI video avatars"},
	{"hourone2", "Hour One", "Hour One", "AI video avatars"},
	{"rephrase2", "Rephrase.ai", "Rephrase", "AI video personalization"},
	{"deepbrain", "DeepBrain AI", "DeepBrain", "AI human video"},
	{"simpleshow", "Simpleshow", "Simpleshow", "AI explainer video"},
	{"steveai", "Steve.AI", "Steve", "AI animation video"},
	{"rawshorts", "Raw Shorts", "Raw Shorts", "AI video maker"},
	{"animaker", "Animaker", "Animaker", "AI animation"},
	{"pencil", "Pencil", "Pencil", "AI ad generation"},
	{"creatopy", "Creatopy", "Creatopy", "AI ad design"},
	{"adcreative", "AdCreative.ai", "AdCreative", "AI ad creatives"},
	{"predis", "Predis.ai", "Predis", "AI social content"},
	{"ocoya", "Ocoya", "Ocoya", "AI social media"},
	{"postwise", "Postwise", "Postwise", "AI social writing"},
	{"vista", "Vista Social", "Vista", "AI social media"},
	{"bufferai", "Buffer AI", "Buffer", "AI social assistant"},
	{"hootsuiteai", "Hootsuite AI", "Hootsuite", "AI social assistant"},
	{"sproutsocial", "Sprout Social", "Sprout", "AI social listening"},
	{"brandwatch", "Brandwatch", "Brandwatch", "AI social listening"},
	{"talkwalker", "Talkwalker", "Talkwalker", "AI social listening"},
	{"sprinklr", "Sprinklr", "Sprinklr", "AI customer experience"},
	{"hootsuite", "Hootsuite", "Hootsuite", "Social media AI"},
	{"later", "Later", "Later", "AI social scheduling"},
	{"metricool", "Metricool", "Metricool", "AI social analytics"},
	{"socialbee", "SocialBee", "SocialBee", "AI social scheduling"},
	{"publer", "Publer", "Publer", "AI social scheduling"},
	{"meetedgar", "MeetEdgar", "MeetEdgar", "AI social automation"},
	{"recurpost", "RecurPost", "RecurPost", "AI social recycling"},
	{"missinglettr", "Missinglettr", "Missinglettr", "AI social campaigns"},
	{"quuu", "Quuu", "Quuu", "AI social curation"},
	{"contentstudio", "ContentStudio", "ContentStudio", "AI content marketing"},
	{"socialpilot", "SocialPilot", "SocialPilot", "AI social media"},
	{"sendible", "Sendible", "Sendible", "AI social media"},
	{"agorapulse", "Agorapulse", "Agorapulse", "AI social media"},
	{"statusbrew", "Statusbrew", "Statusbrew", "AI social media"},
	{"crowdfire", "Crowdfire", "Crowdfire", "AI social media"},
	{"zohosocial", "Zoho Social", "Zoho", "AI social media"},
}
