package goldcmds

// ============================================================================
// GOLD-MD - 1000 NAME FONT DESIGNS (.font1 ... .font1000)
// File: font1000_keys.go
// ============================================================================
// OWNER ORDER: .logo ki tarah hi .font ek category ho. .font likhne par fancy
// boxed menu (FONT1..FONT1000) aata hai. .fontN <name> se us design ka fancy
// text banta hai — name ki jagah font style aata hai, logo waise hi rehta hai.
//
// DESIGN UNIQUENESS: har N = (style, decoration, spacing) ka unique combo:
//   style = (N-1) % 13        -> 13 Unicode letterform families
//   deco  = (N-1)/13 % 400    -> 400 pre/suffix ornament pairs
//   space = (N-1)/13/400      -> 10 letter-spacing treatments
// 13 x 400 x 10 = 5200 combos, is liye N=1..1000 me koi design repeat nahi hota.
// ============================================================================

// FontCount is the number of .font designs (owner order: 1000).
const FontCount = 1000

// fontSrc lists the source characters every alphabet maps, in order:
// A-Z a-z 0-9 (62 runes). Each alphabet string below is the same length.
const fontSrc = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"

// fontAlphabets holds 13 Unicode letterform families, each 62 runes long.
var fontAlphabets = [13]string{
	// Bold
	"𝐀𝐁𝐂𝐃𝐄𝐅𝐆𝐇𝐈𝐉𝐊𝐋𝐌𝐍𝐎𝐏𝐐𝐑𝐒𝐓𝐔𝐕𝐖𝐗𝐘𝐙𝐚𝐛𝐜𝐝𝐞𝐟𝐠𝐡𝐢𝐣𝐤𝐥𝐦𝐧𝐨𝐩𝐪𝐫𝐬𝐭𝐮𝐯𝐰𝐱𝐲𝐳𝟎𝟏𝟐𝟑𝟒𝟓𝟔𝟕𝟖𝟗",
	// Italic
	"𝐴𝐵𝐶𝐷𝐸𝐹𝐺𝐻𝐼𝐽𝐾𝐿𝑀𝑁𝑂𝑃𝑄𝑅𝑆𝑇𝑈𝑉𝑊𝑋𝑌𝑍𝑎𝑏𝑐𝑑𝑒𝑓𝑔ℎ𝑖𝑗𝑘𝑙𝑚𝑛𝑜𝑝𝑞𝑟𝑠𝑡𝑢𝑣𝑤𝑥𝑦𝑧𝟎𝟏𝟐𝟑𝟒𝟓𝟔𝟕𝟖𝟗",
	// Bold Italic
	"𝑨𝑩𝑪𝑫𝑬𝑭𝑮𝑯𝑰𝑱𝑲𝑳𝑴𝑵𝑶𝑷𝑸𝑹𝑺𝑻𝑼𝑽𝑾𝑿𝒀𝒁𝒂𝒃𝒄𝒅𝒆𝒇𝒈𝒉𝒊𝒋𝒌𝒍𝒎𝒏𝒐𝒑𝒒𝒓𝒔𝒕𝒖𝒗𝒘𝒙𝒚𝒛𝟎𝟏𝟐𝟑𝟒𝟓𝟔𝟕𝟖𝟗",
	// Script
	"𝒜ℬ𝒞𝒟ℰℱ𝒢ℋℐ𝒥𝒦ℒℳ𝒩𝒪𝒫𝒬ℛ𝒮𝒯𝒰𝒱𝒲𝒳𝒴𝒵𝒶𝒷𝒸𝒹ℯ𝒻ℊ𝒽𝒾𝒿𝓀𝓁𝓂𝓃ℴ𝓅𝓆𝓇𝓈𝓉𝓊𝓋𝓌𝓍𝓎𝓏𝟎𝟏𝟐𝟑𝟒𝟓𝟔𝟕𝟖𝟗",
	// Bold Script
	"𝓐𝓑𝓒𝓓𝓔𝓕𝓖𝓗𝓘𝓙𝓚𝓛𝓜𝓝𝓞𝓟𝓠𝓡𝓢𝓣𝓤𝓥𝓦𝓧𝓨𝓩𝓪𝓫𝓬𝓭𝓮𝓯𝓰𝓱𝓲𝓳𝓴𝓵𝓶𝓷𝓸𝓹𝓺𝓻𝓼𝓽𝓾𝓿𝔀𝔁𝔂𝔃𝟎𝟏𝟐𝟑𝟒𝟓𝟔𝟕𝟖𝟗",
	// Fraktur
	"𝔄𝔅ℭ𝔇𝔈𝔉𝔊ℌℑ𝔍𝔎𝔏𝔐𝔑𝔒𝔓𝔔ℜ𝔖𝔗𝔘𝔙𝔚𝔛𝔜ℨ𝔞𝔟𝔠𝔡𝔢𝔣𝔤𝔥𝔦𝔧𝔨𝔩𝔪𝔫𝔬𝔭𝔮𝔯𝔰𝔱𝔲𝔳𝔴𝔵𝔶𝔷𝟎𝟏𝟐𝟑𝟒𝟓𝟔𝟕𝟖𝟗",
	// Bold Fraktur
	"𝕬𝕭𝕮𝕯𝕰𝕱𝕲𝕳𝕴𝕵𝕶𝕷𝕸𝕹𝕺𝕻𝕼𝕽𝕾𝕿𝖀𝖁𝖂𝖃𝖄𝖅𝖆𝖇𝖈𝖉𝖊𝖋𝖌𝖍𝖎𝖏𝖐𝖑𝖒𝖓𝖔𝖕𝖖𝖗𝖘𝖙𝖚𝖛𝖜𝖝𝖞𝖟𝟎𝟏𝟐𝟑𝟒𝟓𝟔𝟕𝟖𝟗",
	// Double Struck
	"𝔸𝔹ℂ𝔻𝔼𝔽𝔾ℍ𝕀𝕁𝕂𝕃𝕄ℕ𝕆ℙℚℝ𝕊𝕋𝕌𝕍𝕎𝕏𝕐ℤ𝕒𝕓𝕔𝕕𝕖𝕗𝕘𝕙𝕚𝕛𝕜𝕝𝕞𝕟𝕠𝕡𝕢𝕣𝕤𝕥𝕦𝕧𝕨𝕩𝕪𝕫𝟘𝟙𝟚𝟛𝟜𝟝𝟞𝟟𝟠𝟡",
	// Sans
	"𝖠𝖡𝖢𝖣𝖤𝖥𝖦𝖧𝖨𝖩𝖪𝖫𝖬𝖭𝖮𝖯𝖰𝖱𝖲𝖳𝖴𝖵𝖶𝖷𝖸𝖹𝖺𝖻𝖼𝖽𝖾𝖿𝗀𝗁𝗂𝗃𝗄𝗅𝗆𝗇𝗈𝗉𝗊𝗋𝗌𝗍𝗎𝗏𝗐𝗑𝗒𝗓𝟢𝟣𝟤𝟥𝟦𝟧𝟨𝟩𝟪𝟫",
	// Sans Bold
	"𝗔𝗕𝗖𝗗𝗘𝗙𝗚𝗛𝗜𝗝𝗞𝗟𝗠𝗡𝗢𝗣𝗤𝗥𝗦𝗧𝗨𝗩𝗪𝗫𝗬𝗭𝗮𝗯𝗰𝗱𝗲𝗳𝗴𝗵𝗶𝗷𝗸𝗹𝗺𝗻𝗼𝗽𝗾𝗿𝘀𝘁𝘂𝘃𝘄𝘅𝘆𝘇𝟬𝟭𝟮𝟯𝟰𝟱𝟲𝟳𝟴𝟵",
	// Sans Italic
	"𝘈𝘉𝘊𝘋𝘌𝘍𝘎𝘏𝘐𝘑𝘒𝘓𝘔𝘕𝘖𝘗𝘘𝘙𝘚𝘛𝘜𝘝𝘞𝘟𝘠𝘡𝘢𝘣𝘤𝘥𝘦𝘧𝘨𝘩𝘪𝘫𝘬𝘭𝘮𝘯𝘰𝘱𝘲𝘳𝘴𝘵𝘶𝘷𝘸𝘹𝘺𝘻𝟢𝟣𝟤𝟥𝟦𝟧𝟨𝟩𝟪𝟫",
	// Sans Bold Italic
	"𝘼𝘽𝘾𝘿𝙀𝙁𝙂𝙃𝙄𝙅𝙆𝙇𝙈𝙉𝙊𝙋𝙌𝙍𝙎𝙏𝙐𝙑𝙒𝙓𝙔𝙕𝙖𝙗𝙘𝙙𝙚𝙛𝙜𝙝𝙞𝙟𝙠𝙡𝙢𝙣𝙤𝙥𝙦𝙧𝙨𝙩𝙪𝙫𝙬𝙭𝙮𝙯𝟬𝟭𝟮𝟯𝟰𝟱𝟲𝟳𝟴𝟵",
	// Monospace
	"𝙰𝙱𝙲𝙳𝙴𝙵𝙶𝙷𝙸𝙹𝙺𝙻𝙼𝙽𝙾𝙿𝚀𝚁𝚂𝚃𝚄𝚅𝚆𝚇𝚈𝚉𝚊𝚋𝚌𝚍𝚎𝚏𝚐𝚑𝚒𝚓𝚔𝚕𝚖𝚗𝚘𝚙𝚚𝚛𝚜𝚝𝚞𝚟𝚠𝚡𝚢𝚣𝟶𝟷𝟸𝟹𝟺𝟻𝟼𝟽𝟾𝟿",
}

var fontStyleNames = [13]string{
	"Bold",
	"Italic",
	"Bold Italic",
	"Script",
	"Bold Script",
	"Fraktur",
	"Bold Fraktur",
	"Double Struck",
	"Sans",
	"Sans Bold",
	"Sans Italic",
	"Sans Bold Italic",
	"Monospace",
}

// fontDecorations holds 400 pre/suffix ornament pairs (20 x 20).
var fontDecorations = [400][2]string{
	{"", ""},
	{"", "✧"},
	{"", "꧂"},
	{"", "༻"},
	{"", "彡★"},
	{"", "」"},
	{"", "】"},
	{"", "◢"},
	{"", " ♛"},
	{"", "•✦"},
	{"", " ஜ۩۞۩ஜ"},
	{"", "•´¯`•. "},
	{"", "★"},
	{"", "☬"},
	{"", "✿"},
	{"", "❂"},
	{"", "➤"},
	{"", "⚡"},
	{"", "✵"},
	{"", "❖"},
	{"✧", ""},
	{"✧", "✧"},
	{"✧", "꧂"},
	{"✧", "༻"},
	{"✧", "彡★"},
	{"✧", "」"},
	{"✧", "】"},
	{"✧", "◢"},
	{"✧", " ♛"},
	{"✧", "•✦"},
	{"✧", " ஜ۩۞۩ஜ"},
	{"✧", "•´¯`•. "},
	{"✧", "★"},
	{"✧", "☬"},
	{"✧", "✿"},
	{"✧", "❂"},
	{"✧", "➤"},
	{"✧", "⚡"},
	{"✧", "✵"},
	{"✧", "❖"},
	{"꧁", ""},
	{"꧁", "✧"},
	{"꧁", "꧂"},
	{"꧁", "༻"},
	{"꧁", "彡★"},
	{"꧁", "」"},
	{"꧁", "】"},
	{"꧁", "◢"},
	{"꧁", " ♛"},
	{"꧁", "•✦"},
	{"꧁", " ஜ۩۞۩ஜ"},
	{"꧁", "•´¯`•. "},
	{"꧁", "★"},
	{"꧁", "☬"},
	{"꧁", "✿"},
	{"꧁", "❂"},
	{"꧁", "➤"},
	{"꧁", "⚡"},
	{"꧁", "✵"},
	{"꧁", "❖"},
	{"༺", ""},
	{"༺", "✧"},
	{"༺", "꧂"},
	{"༺", "༻"},
	{"༺", "彡★"},
	{"༺", "」"},
	{"༺", "】"},
	{"༺", "◢"},
	{"༺", " ♛"},
	{"༺", "•✦"},
	{"༺", " ஜ۩۞۩ஜ"},
	{"༺", "•´¯`•. "},
	{"༺", "★"},
	{"༺", "☬"},
	{"༺", "✿"},
	{"༺", "❂"},
	{"༺", "➤"},
	{"༺", "⚡"},
	{"༺", "✵"},
	{"༺", "❖"},
	{"★彡", ""},
	{"★彡", "✧"},
	{"★彡", "꧂"},
	{"★彡", "༻"},
	{"★彡", "彡★"},
	{"★彡", "」"},
	{"★彡", "】"},
	{"★彡", "◢"},
	{"★彡", " ♛"},
	{"★彡", "•✦"},
	{"★彡", " ஜ۩۞۩ஜ"},
	{"★彡", "•´¯`•. "},
	{"★彡", "★"},
	{"★彡", "☬"},
	{"★彡", "✿"},
	{"★彡", "❂"},
	{"★彡", "➤"},
	{"★彡", "⚡"},
	{"★彡", "✵"},
	{"★彡", "❖"},
	{"「", ""},
	{"「", "✧"},
	{"「", "꧂"},
	{"「", "༻"},
	{"「", "彡★"},
	{"「", "」"},
	{"「", "】"},
	{"「", "◢"},
	{"「", " ♛"},
	{"「", "•✦"},
	{"「", " ஜ۩۞۩ஜ"},
	{"「", "•´¯`•. "},
	{"「", "★"},
	{"「", "☬"},
	{"「", "✿"},
	{"「", "❂"},
	{"「", "➤"},
	{"「", "⚡"},
	{"「", "✵"},
	{"「", "❖"},
	{"【", ""},
	{"【", "✧"},
	{"【", "꧂"},
	{"【", "༻"},
	{"【", "彡★"},
	{"【", "」"},
	{"【", "】"},
	{"【", "◢"},
	{"【", " ♛"},
	{"【", "•✦"},
	{"【", " ஜ۩۞۩ஜ"},
	{"【", "•´¯`•. "},
	{"【", "★"},
	{"【", "☬"},
	{"【", "✿"},
	{"【", "❂"},
	{"【", "➤"},
	{"【", "⚡"},
	{"【", "✵"},
	{"【", "❖"},
	{"◤", ""},
	{"◤", "✧"},
	{"◤", "꧂"},
	{"◤", "༻"},
	{"◤", "彡★"},
	{"◤", "」"},
	{"◤", "】"},
	{"◤", "◢"},
	{"◤", " ♛"},
	{"◤", "•✦"},
	{"◤", " ஜ۩۞۩ஜ"},
	{"◤", "•´¯`•. "},
	{"◤", "★"},
	{"◤", "☬"},
	{"◤", "✿"},
	{"◤", "❂"},
	{"◤", "➤"},
	{"◤", "⚡"},
	{"◤", "✵"},
	{"◤", "❖"},
	{"♛ ", ""},
	{"♛ ", "✧"},
	{"♛ ", "꧂"},
	{"♛ ", "༻"},
	{"♛ ", "彡★"},
	{"♛ ", "」"},
	{"♛ ", "】"},
	{"♛ ", "◢"},
	{"♛ ", " ♛"},
	{"♛ ", "•✦"},
	{"♛ ", " ஜ۩۞۩ஜ"},
	{"♛ ", "•´¯`•. "},
	{"♛ ", "★"},
	{"♛ ", "☬"},
	{"♛ ", "✿"},
	{"♛ ", "❂"},
	{"♛ ", "➤"},
	{"♛ ", "⚡"},
	{"♛ ", "✵"},
	{"♛ ", "❖"},
	{"✦•", ""},
	{"✦•", "✧"},
	{"✦•", "꧂"},
	{"✦•", "༻"},
	{"✦•", "彡★"},
	{"✦•", "」"},
	{"✦•", "】"},
	{"✦•", "◢"},
	{"✦•", " ♛"},
	{"✦•", "•✦"},
	{"✦•", " ஜ۩۞۩ஜ"},
	{"✦•", "•´¯`•. "},
	{"✦•", "★"},
	{"✦•", "☬"},
	{"✦•", "✿"},
	{"✦•", "❂"},
	{"✦•", "➤"},
	{"✦•", "⚡"},
	{"✦•", "✵"},
	{"✦•", "❖"},
	{"ஜ۩۞۩ஜ ", ""},
	{"ஜ۩۞۩ஜ ", "✧"},
	{"ஜ۩۞۩ஜ ", "꧂"},
	{"ஜ۩۞۩ஜ ", "༻"},
	{"ஜ۩۞۩ஜ ", "彡★"},
	{"ஜ۩۞۩ஜ ", "」"},
	{"ஜ۩۞۩ஜ ", "】"},
	{"ஜ۩۞۩ஜ ", "◢"},
	{"ஜ۩۞۩ஜ ", " ♛"},
	{"ஜ۩۞۩ஜ ", "•✦"},
	{"ஜ۩۞۩ஜ ", " ஜ۩۞۩ஜ"},
	{"ஜ۩۞۩ஜ ", "•´¯`•. "},
	{"ஜ۩۞۩ஜ ", "★"},
	{"ஜ۩۞۩ஜ ", "☬"},
	{"ஜ۩۞۩ஜ ", "✿"},
	{"ஜ۩۞۩ஜ ", "❂"},
	{"ஜ۩۞۩ஜ ", "➤"},
	{"ஜ۩۞۩ஜ ", "⚡"},
	{"ஜ۩۞۩ஜ ", "✵"},
	{"ஜ۩۞۩ஜ ", "❖"},
	{"•´¯`•. ", ""},
	{"•´¯`•. ", "✧"},
	{"•´¯`•. ", "꧂"},
	{"•´¯`•. ", "༻"},
	{"•´¯`•. ", "彡★"},
	{"•´¯`•. ", "」"},
	{"•´¯`•. ", "】"},
	{"•´¯`•. ", "◢"},
	{"•´¯`•. ", " ♛"},
	{"•´¯`•. ", "•✦"},
	{"•´¯`•. ", " ஜ۩۞۩ஜ"},
	{"•´¯`•. ", "•´¯`•. "},
	{"•´¯`•. ", "★"},
	{"•´¯`•. ", "☬"},
	{"•´¯`•. ", "✿"},
	{"•´¯`•. ", "❂"},
	{"•´¯`•. ", "➤"},
	{"•´¯`•. ", "⚡"},
	{"•´¯`•. ", "✵"},
	{"•´¯`•. ", "❖"},
	{"★", ""},
	{"★", "✧"},
	{"★", "꧂"},
	{"★", "༻"},
	{"★", "彡★"},
	{"★", "」"},
	{"★", "】"},
	{"★", "◢"},
	{"★", " ♛"},
	{"★", "•✦"},
	{"★", " ஜ۩۞۩ஜ"},
	{"★", "•´¯`•. "},
	{"★", "★"},
	{"★", "☬"},
	{"★", "✿"},
	{"★", "❂"},
	{"★", "➤"},
	{"★", "⚡"},
	{"★", "✵"},
	{"★", "❖"},
	{"☬", ""},
	{"☬", "✧"},
	{"☬", "꧂"},
	{"☬", "༻"},
	{"☬", "彡★"},
	{"☬", "」"},
	{"☬", "】"},
	{"☬", "◢"},
	{"☬", " ♛"},
	{"☬", "•✦"},
	{"☬", " ஜ۩۞۩ஜ"},
	{"☬", "•´¯`•. "},
	{"☬", "★"},
	{"☬", "☬"},
	{"☬", "✿"},
	{"☬", "❂"},
	{"☬", "➤"},
	{"☬", "⚡"},
	{"☬", "✵"},
	{"☬", "❖"},
	{"✿", ""},
	{"✿", "✧"},
	{"✿", "꧂"},
	{"✿", "༻"},
	{"✿", "彡★"},
	{"✿", "」"},
	{"✿", "】"},
	{"✿", "◢"},
	{"✿", " ♛"},
	{"✿", "•✦"},
	{"✿", " ஜ۩۞۩ஜ"},
	{"✿", "•´¯`•. "},
	{"✿", "★"},
	{"✿", "☬"},
	{"✿", "✿"},
	{"✿", "❂"},
	{"✿", "➤"},
	{"✿", "⚡"},
	{"✿", "✵"},
	{"✿", "❖"},
	{"❂", ""},
	{"❂", "✧"},
	{"❂", "꧂"},
	{"❂", "༻"},
	{"❂", "彡★"},
	{"❂", "」"},
	{"❂", "】"},
	{"❂", "◢"},
	{"❂", " ♛"},
	{"❂", "•✦"},
	{"❂", " ஜ۩۞۩ஜ"},
	{"❂", "•´¯`•. "},
	{"❂", "★"},
	{"❂", "☬"},
	{"❂", "✿"},
	{"❂", "❂"},
	{"❂", "➤"},
	{"❂", "⚡"},
	{"❂", "✵"},
	{"❂", "❖"},
	{"➤", ""},
	{"➤", "✧"},
	{"➤", "꧂"},
	{"➤", "༻"},
	{"➤", "彡★"},
	{"➤", "」"},
	{"➤", "】"},
	{"➤", "◢"},
	{"➤", " ♛"},
	{"➤", "•✦"},
	{"➤", " ஜ۩۞۩ஜ"},
	{"➤", "•´¯`•. "},
	{"➤", "★"},
	{"➤", "☬"},
	{"➤", "✿"},
	{"➤", "❂"},
	{"➤", "➤"},
	{"➤", "⚡"},
	{"➤", "✵"},
	{"➤", "❖"},
	{"⚡", ""},
	{"⚡", "✧"},
	{"⚡", "꧂"},
	{"⚡", "༻"},
	{"⚡", "彡★"},
	{"⚡", "」"},
	{"⚡", "】"},
	{"⚡", "◢"},
	{"⚡", " ♛"},
	{"⚡", "•✦"},
	{"⚡", " ஜ۩۞۩ஜ"},
	{"⚡", "•´¯`•. "},
	{"⚡", "★"},
	{"⚡", "☬"},
	{"⚡", "✿"},
	{"⚡", "❂"},
	{"⚡", "➤"},
	{"⚡", "⚡"},
	{"⚡", "✵"},
	{"⚡", "❖"},
	{"✵", ""},
	{"✵", "✧"},
	{"✵", "꧂"},
	{"✵", "༻"},
	{"✵", "彡★"},
	{"✵", "」"},
	{"✵", "】"},
	{"✵", "◢"},
	{"✵", " ♛"},
	{"✵", "•✦"},
	{"✵", " ஜ۩۞۩ஜ"},
	{"✵", "•´¯`•. "},
	{"✵", "★"},
	{"✵", "☬"},
	{"✵", "✿"},
	{"✵", "❂"},
	{"✵", "➤"},
	{"✵", "⚡"},
	{"✵", "✵"},
	{"✵", "❖"},
	{"❖", ""},
	{"❖", "✧"},
	{"❖", "꧂"},
	{"❖", "༻"},
	{"❖", "彡★"},
	{"❖", "」"},
	{"❖", "】"},
	{"❖", "◢"},
	{"❖", " ♛"},
	{"❖", "•✦"},
	{"❖", " ஜ۩۞۩ஜ"},
	{"❖", "•´¯`•. "},
	{"❖", "★"},
	{"❖", "☬"},
	{"❖", "✿"},
	{"❖", "❂"},
	{"❖", "➤"},
	{"❖", "⚡"},
	{"❖", "✵"},
	{"❖", "❖"},
}

var fontDecorationNames = [400]string{
	"Plain Plain",
	"Plain Twinkle",
	"Plain Finale",
	"Plain Arch",
	"Plain Comet",
	"Plain Quote",
	"Plain Bracket",
	"Plain Corner",
	"Plain Crown",
	"Plain Burst",
	"Plain Royale",
	"Plain Dotted",
	"Plain Star",
	"Plain Medal",
	"Plain Blossom",
	"Plain Orb",
	"Plain Arrow",
	"Plain Bolt",
	"Plain Glow",
	"Plain Gem",
	"Sparkle Plain",
	"Sparkle Twinkle",
	"Sparkle Finale",
	"Sparkle Arch",
	"Sparkle Comet",
	"Sparkle Quote",
	"Sparkle Bracket",
	"Sparkle Corner",
	"Sparkle Crown",
	"Sparkle Burst",
	"Sparkle Royale",
	"Sparkle Dotted",
	"Sparkle Star",
	"Sparkle Medal",
	"Sparkle Blossom",
	"Sparkle Orb",
	"Sparkle Arrow",
	"Sparkle Bolt",
	"Sparkle Glow",
	"Sparkle Gem",
	"Anthem Plain",
	"Anthem Twinkle",
	"Anthem Finale",
	"Anthem Arch",
	"Anthem Comet",
	"Anthem Quote",
	"Anthem Bracket",
	"Anthem Corner",
	"Anthem Crown",
	"Anthem Burst",
	"Anthem Royale",
	"Anthem Dotted",
	"Anthem Star",
	"Anthem Medal",
	"Anthem Blossom",
	"Anthem Orb",
	"Anthem Arrow",
	"Anthem Bolt",
	"Anthem Glow",
	"Anthem Gem",
	"Arch Plain",
	"Arch Twinkle",
	"Arch Finale",
	"Arch Arch",
	"Arch Comet",
	"Arch Quote",
	"Arch Bracket",
	"Arch Corner",
	"Arch Crown",
	"Arch Burst",
	"Arch Royale",
	"Arch Dotted",
	"Arch Star",
	"Arch Medal",
	"Arch Blossom",
	"Arch Orb",
	"Arch Arrow",
	"Arch Bolt",
	"Arch Glow",
	"Arch Gem",
	"Star Trail Plain",
	"Star Trail Twinkle",
	"Star Trail Finale",
	"Star Trail Arch",
	"Star Trail Comet",
	"Star Trail Quote",
	"Star Trail Bracket",
	"Star Trail Corner",
	"Star Trail Crown",
	"Star Trail Burst",
	"Star Trail Royale",
	"Star Trail Dotted",
	"Star Trail Star",
	"Star Trail Medal",
	"Star Trail Blossom",
	"Star Trail Orb",
	"Star Trail Arrow",
	"Star Trail Bolt",
	"Star Trail Glow",
	"Star Trail Gem",
	"Quote Plain",
	"Quote Twinkle",
	"Quote Finale",
	"Quote Arch",
	"Quote Comet",
	"Quote Quote",
	"Quote Bracket",
	"Quote Corner",
	"Quote Crown",
	"Quote Burst",
	"Quote Royale",
	"Quote Dotted",
	"Quote Star",
	"Quote Medal",
	"Quote Blossom",
	"Quote Orb",
	"Quote Arrow",
	"Quote Bolt",
	"Quote Glow",
	"Quote Gem",
	"Bracket Plain",
	"Bracket Twinkle",
	"Bracket Finale",
	"Bracket Arch",
	"Bracket Comet",
	"Bracket Quote",
	"Bracket Bracket",
	"Bracket Corner",
	"Bracket Crown",
	"Bracket Burst",
	"Bracket Royale",
	"Bracket Dotted",
	"Bracket Star",
	"Bracket Medal",
	"Bracket Blossom",
	"Bracket Orb",
	"Bracket Arrow",
	"Bracket Bolt",
	"Bracket Glow",
	"Bracket Gem",
	"Corner Plain",
	"Corner Twinkle",
	"Corner Finale",
	"Corner Arch",
	"Corner Comet",
	"Corner Quote",
	"Corner Bracket",
	"Corner Corner",
	"Corner Crown",
	"Corner Burst",
	"Corner Royale",
	"Corner Dotted",
	"Corner Star",
	"Corner Medal",
	"Corner Blossom",
	"Corner Orb",
	"Corner Arrow",
	"Corner Bolt",
	"Corner Glow",
	"Corner Gem",
	"Crown Plain",
	"Crown Twinkle",
	"Crown Finale",
	"Crown Arch",
	"Crown Comet",
	"Crown Quote",
	"Crown Bracket",
	"Crown Corner",
	"Crown Crown",
	"Crown Burst",
	"Crown Royale",
	"Crown Dotted",
	"Crown Star",
	"Crown Medal",
	"Crown Blossom",
	"Crown Orb",
	"Crown Arrow",
	"Crown Bolt",
	"Crown Glow",
	"Crown Gem",
	"Burst Plain",
	"Burst Twinkle",
	"Burst Finale",
	"Burst Arch",
	"Burst Comet",
	"Burst Quote",
	"Burst Bracket",
	"Burst Corner",
	"Burst Crown",
	"Burst Burst",
	"Burst Royale",
	"Burst Dotted",
	"Burst Star",
	"Burst Medal",
	"Burst Blossom",
	"Burst Orb",
	"Burst Arrow",
	"Burst Bolt",
	"Burst Glow",
	"Burst Gem",
	"Royale Plain",
	"Royale Twinkle",
	"Royale Finale",
	"Royale Arch",
	"Royale Comet",
	"Royale Quote",
	"Royale Bracket",
	"Royale Corner",
	"Royale Crown",
	"Royale Burst",
	"Royale Royale",
	"Royale Dotted",
	"Royale Star",
	"Royale Medal",
	"Royale Blossom",
	"Royale Orb",
	"Royale Arrow",
	"Royale Bolt",
	"Royale Glow",
	"Royale Gem",
	"Dotted Plain",
	"Dotted Twinkle",
	"Dotted Finale",
	"Dotted Arch",
	"Dotted Comet",
	"Dotted Quote",
	"Dotted Bracket",
	"Dotted Corner",
	"Dotted Crown",
	"Dotted Burst",
	"Dotted Royale",
	"Dotted Dotted",
	"Dotted Star",
	"Dotted Medal",
	"Dotted Blossom",
	"Dotted Orb",
	"Dotted Arrow",
	"Dotted Bolt",
	"Dotted Glow",
	"Dotted Gem",
	"Star Plain",
	"Star Twinkle",
	"Star Finale",
	"Star Arch",
	"Star Comet",
	"Star Quote",
	"Star Bracket",
	"Star Corner",
	"Star Crown",
	"Star Burst",
	"Star Royale",
	"Star Dotted",
	"Star Star",
	"Star Medal",
	"Star Blossom",
	"Star Orb",
	"Star Arrow",
	"Star Bolt",
	"Star Glow",
	"Star Gem",
	"Medal Plain",
	"Medal Twinkle",
	"Medal Finale",
	"Medal Arch",
	"Medal Comet",
	"Medal Quote",
	"Medal Bracket",
	"Medal Corner",
	"Medal Crown",
	"Medal Burst",
	"Medal Royale",
	"Medal Dotted",
	"Medal Star",
	"Medal Medal",
	"Medal Blossom",
	"Medal Orb",
	"Medal Arrow",
	"Medal Bolt",
	"Medal Glow",
	"Medal Gem",
	"Blossom Plain",
	"Blossom Twinkle",
	"Blossom Finale",
	"Blossom Arch",
	"Blossom Comet",
	"Blossom Quote",
	"Blossom Bracket",
	"Blossom Corner",
	"Blossom Crown",
	"Blossom Burst",
	"Blossom Royale",
	"Blossom Dotted",
	"Blossom Star",
	"Blossom Medal",
	"Blossom Blossom",
	"Blossom Orb",
	"Blossom Arrow",
	"Blossom Bolt",
	"Blossom Glow",
	"Blossom Gem",
	"Orb Plain",
	"Orb Twinkle",
	"Orb Finale",
	"Orb Arch",
	"Orb Comet",
	"Orb Quote",
	"Orb Bracket",
	"Orb Corner",
	"Orb Crown",
	"Orb Burst",
	"Orb Royale",
	"Orb Dotted",
	"Orb Star",
	"Orb Medal",
	"Orb Blossom",
	"Orb Orb",
	"Orb Arrow",
	"Orb Bolt",
	"Orb Glow",
	"Orb Gem",
	"Arrow Plain",
	"Arrow Twinkle",
	"Arrow Finale",
	"Arrow Arch",
	"Arrow Comet",
	"Arrow Quote",
	"Arrow Bracket",
	"Arrow Corner",
	"Arrow Crown",
	"Arrow Burst",
	"Arrow Royale",
	"Arrow Dotted",
	"Arrow Star",
	"Arrow Medal",
	"Arrow Blossom",
	"Arrow Orb",
	"Arrow Arrow",
	"Arrow Bolt",
	"Arrow Glow",
	"Arrow Gem",
	"Bolt Plain",
	"Bolt Twinkle",
	"Bolt Finale",
	"Bolt Arch",
	"Bolt Comet",
	"Bolt Quote",
	"Bolt Bracket",
	"Bolt Corner",
	"Bolt Crown",
	"Bolt Burst",
	"Bolt Royale",
	"Bolt Dotted",
	"Bolt Star",
	"Bolt Medal",
	"Bolt Blossom",
	"Bolt Orb",
	"Bolt Arrow",
	"Bolt Bolt",
	"Bolt Glow",
	"Bolt Gem",
	"Glow Plain",
	"Glow Twinkle",
	"Glow Finale",
	"Glow Arch",
	"Glow Comet",
	"Glow Quote",
	"Glow Bracket",
	"Glow Corner",
	"Glow Crown",
	"Glow Burst",
	"Glow Royale",
	"Glow Dotted",
	"Glow Star",
	"Glow Medal",
	"Glow Blossom",
	"Glow Orb",
	"Glow Arrow",
	"Glow Bolt",
	"Glow Glow",
	"Glow Gem",
	"Gem Plain",
	"Gem Twinkle",
	"Gem Finale",
	"Gem Arch",
	"Gem Comet",
	"Gem Quote",
	"Gem Bracket",
	"Gem Corner",
	"Gem Crown",
	"Gem Burst",
	"Gem Royale",
	"Gem Dotted",
	"Gem Star",
	"Gem Medal",
	"Gem Blossom",
	"Gem Orb",
	"Gem Arrow",
	"Gem Bolt",
	"Gem Glow",
	"Gem Gem",
}

// fontSpacings: how the gap between letters is filled.
var fontSpacings = [10]string{
	"",
	" ",
	"  ",
	"·",
	"•",
	"✦",
	"×",
	"-",
	"|",
	"◦",
}

var fontSpacingNames = [10]string{
	"Tight",
	"Single Space",
	"Double Space",
	"Dot",
	"Bullet",
	"Spark",
	"Cross",
	"Dash",
	"Bar",
	"Ring",
}
