package goldcmds

// Data for the 1000 menu/bot designs (owner order). MenuStyleCount and the
// resolver live in menustyle.go; style 1 is the hand-written classic look.

// styleSymbols is the signature-symbol pool, one unique symbol per style
// (index 0 backs the classic style).
var styleSymbols = []string{
	"🔰", "←", "↑", "→", "↓", "↔", "↕", "↖", "↗", "↘", "↙", "↚",
	"↛", "↜", "↝", "↞", "↟", "↠", "↡", "↢", "↣", "↤", "↥", "↦",
	"↧", "↨", "↩", "↪", "↫", "↬", "↭", "↮", "↯", "↰", "↱", "↲",
	"↳", "↴", "↵", "↶", "↷", "↸", "↹", "↺", "↻", "↼", "↽", "↾",
	"↿", "⇀", "⇁", "⇂", "⇃", "⇄", "⇅", "⇆", "⇇", "⇈", "⇉", "⇊",
	"⇋", "⇌", "⇍", "⇎", "⇏", "⇐", "⇑", "⇒", "⇓", "⇔", "⇕", "⇖",
	"⇗", "⇘", "⇙", "⇚", "⇛", "⇜", "⇝", "⇞", "⇟", "⇠", "⇡", "⇢",
	"⇣", "⇤", "⇥", "⇦", "⇧", "⇨", "⇩", "⇪", "⇫", "⇬", "⇭", "⇮",
	"⇯", "⇰", "⇱", "⇲", "⇳", "⇴", "⇵", "⇶", "⇷", "⇸", "⇹", "⇺",
	"⇻", "⇼", "⇽", "⇾", "⇿", "∀", "∁", "∂", "∃", "∄", "∅", "∆",
	"∇", "∈", "∉", "∊", "∋", "∌", "∍", "∎", "∏", "∐", "∑", "−",
	"∓", "∔", "∕", "∖", "∗", "∘", "∙", "√", "∛", "∜", "∝", "∞",
	"∟", "∠", "∡", "∢", "∣", "∤", "∥", "∦", "∧", "∨", "∩", "∪",
	"∫", "∬", "∭", "∮", "∯", "∰", "∱", "∲", "∳", "∴", "∵", "∶",
	"∷", "∸", "∹", "∺", "∻", "∼", "∽", "∾", "∿", "≀", "≁", "≂",
	"≃", "≄", "≅", "≆", "≇", "≈", "≉", "≊", "≋", "≌", "≍", "≎",
	"≏", "≐", "≑", "≒", "≓", "≔", "≕", "≖", "≗", "≘", "≙", "≚",
	"≛", "≜", "≝", "≞", "≟", "≠", "≡", "≢", "≣", "≤", "≥", "≦",
	"≧", "≨", "≩", "≪", "≫", "≬", "≭", "≮", "≯", "≰", "≱", "≲",
	"≳", "≴", "≵", "≶", "≷", "≸", "≹", "≺", "≻", "≼", "≽", "≾",
	"≿", "⊀", "⊁", "⊂", "⊃", "⊄", "⊅", "⊆", "⊇", "⊈", "⊉", "⊊",
	"⊋", "⊌", "⊍", "⊎", "⊏", "⊐", "⊑", "⊒", "⊓", "⊔", "⊕", "⊖",
	"⊗", "⊘", "⊙", "⊚", "⊛", "⊜", "⊝", "⊞", "⊟", "⊠", "⊡", "⊢",
	"⊣", "⊤", "⊥", "⊦", "⊧", "⊨", "⊩", "⊪", "⊫", "⊬", "⊭", "⊮",
	"⊯", "⊰", "⊱", "⊲", "⊳", "⊴", "⊵", "⊶", "⊷", "⊸", "⊹", "⊺",
	"⊻", "⊼", "⊽", "⊾", "⊿", "⋀", "⋁", "⋂", "⋃", "⋄", "⋅", "⋆",
	"⋇", "⋈", "⋉", "⋊", "⋋", "⋌", "⋍", "⋎", "⋏", "⋐", "⋑", "⋒",
	"⋓", "⋔", "⋕", "⋖", "⋗", "⋘", "⋙", "⋚", "⋛", "⋜", "⋝", "⋞",
	"⋟", "⋠", "⋡", "⋢", "⋣", "⋤", "⋥", "⋦", "⋧", "⋨", "⋩", "⋪",
	"⋫", "⋬", "⋭", "⋮", "⋯", "⋰", "⋱", "⋲", "⋳", "⋴", "⋵", "⋶",
	"⋷", "⋸", "⋹", "⋺", "⋻", "⋼", "⋽", "⋾", "⋿", "⌀", "⌁", "⌂",
	"⌃", "⌄", "⌅", "⌆", "⌇", "⌈", "⌉", "⌊", "⌋", "⌌", "⌍", "⌎",
	"⌏", "⌐", "⌑", "⌒", "⌓", "⌔", "⌕", "⌖", "⌗", "⌘", "⌙", "⌚",
	"⌛", "⌜", "⌝", "⌞", "⌟", "⌠", "⌡", "⌢", "⌣", "⌤", "⌥", "⌦",
	"⌧", "⌨", "〈", "〉", "⌫", "⌬", "⌭", "⌮", "⌯", "⌰", "⌱", "⌲",
	"⌳", "⌴", "⌵", "⌶", "⌷", "⌸", "⌹", "⌺", "⌻", "⌼", "⌽", "⌾",
	"⌿", "⍀", "⍁", "⍂", "⍃", "⍄", "⍅", "⍆", "⍇", "⍈", "⍉", "⍊",
	"⍋", "⍌", "⍍", "⍎", "⍏", "⍐", "⍑", "⍒", "⍓", "⍔", "⍕", "⍖",
	"⍗", "⍘", "⍙", "⍚", "⍛", "⍜", "⍝", "⍞", "⍟", "⍠", "⍡", "⍢",
	"⍣", "⍤", "⍥", "⍦", "⍧", "⍨", "⍩", "⍪", "⍫", "⍬", "⍭", "⍮",
	"⍯", "⍰", "⍱", "⍲", "⍳", "⍴", "⍵", "⍶", "⍷", "⍸", "⍹", "⍺",
	"⍻", "⍼", "⍽", "⍾", "⍿", "⎀", "⎁", "⎂", "⎃", "⎄", "⎅", "⎆",
	"⎇", "⎈", "⎉", "⎊", "⎋", "⎌", "⎍", "⎎", "⎏", "⎐", "⎑", "⎒",
	"⎓", "⎔", "⎕", "⎖", "⎗", "⎘", "⎙", "⎚", "⎛", "⎜", "⎝", "⎞",
	"⎟", "⎠", "⎡", "⎢", "⎣", "⎤", "⎥", "⎦", "⎧", "⎨", "⎩", "⎪",
	"⎫", "⎬", "⎭", "⎮", "⎯", "⎰", "⎱", "⎲", "⎳", "⎴", "⎵", "⎶",
	"⎷", "⎸", "⎹", "⎺", "⎻", "⎼", "⎽", "⎾", "⎿", "⏀", "⏁", "⏂",
	"⏃", "⏄", "⏅", "⏆", "⏇", "⏈", "⏉", "⏊", "⏋", "⏌", "⏍", "⏎",
	"⏏", "⏐", "⏑", "⏒", "⏓", "⏔", "⏕", "⏖", "⏗", "⏘", "⏙", "⏚",
	"⏛", "⏜", "⏝", "⏞", "⏟", "⏠", "⏡", "⏢", "⏣", "⏤", "⏥", "⏦",
	"⏧", "⏨", "⏩", "⏪", "⏫", "⏬", "⏭", "⏮", "⏯", "⏰", "⏱", "⏲",
	"⏳", "⏴", "⏵", "⏶", "⏷", "⏸", "⏹", "⏺", "⏻", "⏼", "⏽", "⏾",
	"⏿", "␀", "␁", "␂", "␃", "␄", "␅", "␆", "␇", "␈", "␉", "␊",
	"␋", "␌", "␍", "␎", "␏", "␐", "␑", "␒", "␓", "␔", "␕", "␖",
	"␗", "␘", "␙", "␚", "␛", "␜", "␝", "␞", "␟", "␠", "␡", "␢",
	"␣", "␤", "␥", "␦", "⑀", "⑁", "⑂", "⑃", "⑄", "⑅", "⑆", "⑇",
	"⑈", "⑉", "⑊", "⒜", "⒝", "⒞", "⒟", "⒠", "⒡", "⒢", "⒣", "⒤",
	"⒥", "⒦", "⒧", "⒨", "⒩", "⒪", "⒫", "⒬", "⒭", "⒮", "⒯", "⒰",
	"⒱", "⒲", "⒳", "⒴", "⒵", "Ⓐ", "Ⓑ", "Ⓒ", "Ⓓ", "Ⓔ", "Ⓕ", "Ⓖ",
	"Ⓗ", "Ⓘ", "Ⓙ", "Ⓚ", "Ⓛ", "Ⓜ", "Ⓝ", "Ⓞ", "Ⓟ", "Ⓠ", "Ⓡ", "Ⓢ",
	"Ⓣ", "Ⓤ", "Ⓥ", "Ⓦ", "Ⓧ", "Ⓨ", "Ⓩ", "ⓐ", "ⓑ", "ⓒ", "ⓓ", "ⓔ",
	"ⓕ", "ⓖ", "ⓗ", "ⓘ", "ⓙ", "ⓚ", "ⓛ", "ⓜ", "ⓝ", "ⓞ", "ⓟ", "ⓠ",
	"ⓡ", "ⓢ", "ⓣ", "ⓤ", "ⓥ", "ⓦ", "ⓧ", "ⓨ", "ⓩ", "─", "━", "│",
	"┃", "┄", "┅", "┆", "┇", "┈", "┉", "┊", "┋", "┌", "┍", "┎",
	"┏", "┐", "┑", "┒", "┓", "└", "┕", "┖", "┗", "┘", "┙", "┚",
	"┛", "├", "┝", "┞", "┟", "┠", "┡", "┢", "┣", "┤", "┥", "┦",
	"┧", "┨", "┩", "┪", "┫", "┬", "┭", "┮", "┯", "┰", "┱", "┲",
	"┳", "┴", "┵", "┶", "┷", "┸", "┹", "┺", "┻", "┼", "┽", "┾",
	"┿", "╀", "╁", "╂", "╃", "╄", "╅", "╆", "╇", "╈", "╉", "╊",
	"╋", "╌", "╍", "╎", "╏", "═", "║", "╒", "╓", "╔", "╕", "╖",
	"╗", "╘", "╙", "╚", "╛", "╜", "╝", "╞", "╟", "╠", "╡", "╢",
	"╣", "╤", "╥", "╦", "╧", "╨", "╩", "╪", "╫", "╬", "╭", "╮",
	"╯", "╰", "╱", "╲", "╳", "╴", "╵", "╶", "╷", "╸", "╹", "╺",
	"╻", "╼", "╽", "╾", "╿", "▀", "▁", "▂", "▃", "▄", "▅", "▆",
	"▇", "█", "▉", "▊", "▋", "▌", "▍", "▎", "▏", "▐", "░", "▒",
	"▓", "▔", "▕", "▖", "▗", "▘", "▙", "▚", "▛", "▜", "▝", "▞",
	"▟", "■", "□", "▢", "▣", "▤", "▥", "▦", "▧", "▨", "▩", "▪",
	"▫", "▬", "▭", "▮", "▯", "▰", "▱", "▲", "△", "▴", "▵", "▶",
	"▷", "▸", "▹", "►", "▻", "▼", "▽", "▾", "▿", "◀", "◁", "◂",
	"◃", "◄", "◅", "◆", "◇", "◈", "◉", "◊", "○", "◌", "◍", "◎",
	"●", "◐", "◑", "◒", "◓", "◔", "◕", "◖", "◗", "◘", "◙", "◚",
	"◛", "◜", "◝", "◞", "◟", "◠", "◡", "◢", "◣", "◤", "◥", "◦",
	"◧", "◨", "◩", "◪", "◫", "◬", "◭", "◮", "◯", "◰", "◱", "◲",
	"◳", "◴", "◵", "◶",
}

// styleBorders are the 50 frame templates. {S} = the style symbol.
var styleBorders = []struct{ Top, Bot string }{
	{"╔════ ≪ • {S} • ≫ ════╗", "╚════ ≪ • {S} • ≫ ════╝"},
	{"✦━━━━ ❖ {S} ❖ ━━━━✦", "✦━━━━ ❖ {S} ❖ ━━━━✦"},
	{"╔═◤ {S} ◥════════╗", "╚═◣ {S} ◢════════╝"},
	{"✧･ﾟ: ✩ {S} ✩ :･ﾟ✧", "✧･ﾟ: ✩ {S} ✩ :･ﾟ✧"},
	{"╔══════【 {S} 】══════╗", "╚══════【 {S} 】══════╝"},
	{"▀▄▀▄▀▄ {S} ▄▀▄▀▄▀", "▀▄▀▄▀▄ {S} ▄▀▄▀▄▀"},
	{"╭━━━━❰ {S} ❱━━━━╮", "╰━━━━❰ {S} ❱━━━━╯"},
	{"⋆｡°✩ {S} ✩°｡⋆", "⋆｡°✩ {S} ✩°｡⋆"},
	{"╔╦═══ ≼ {S} ≽ ═══╦╗", "╚╩═══ ≼ {S} ≽ ═══╩╝"},
	{"❃━❃━❃❃ {S} ❃❃━❃━❃", "❃━❃━❃❃ {S} ❃❃━❃━❃"},
	{"╔─═══ ≪ {S} ≫ ═══─╗", "╚─═══ ≪ {S} ≫ ═══─╝"},
	{"◆━━━━━━ {S} ━━━━━━◆", "◆━━━━━━ {S} ━━━━━━◆"},
	{"╔❰❰ {S} ❱❱═══════╗", "╚❰❰ {S} ❱❱═══════╝"},
	{"✿•°¯`•• {S} ••´¯°•✿", "✿•°¯`•• {S} ••´¯°•✿"},
	{"╔◢◤ {S} ◥◣══════╗", "╚◥◣ {S} ◢◤══════╝"},
	{"★彡 {S} 彡★", "★彡 {S} 彡★"},
	{"╭─━━━━ {S} ━━━━─╮", "╰─━━━━ {S} ━━━━─╯"},
	{"◤◢◤◢ {S} ◢◤◢◤", "◤◢◤◢ {S} ◢◤◢◤"},
	{"╔▒▒▒▒ {S} ▒▒▒▒╗", "╚▒▒▒▒ {S} ▒▒▒▒╝"},
	{"⟪⟪⟪ {S} ⟫⟫⟫", "⟪⟪⟪ {S} ⟫⟫⟫"},
	{"╔░▒▓ {S} ▓▒░╗", "╚░▒▓ {S} ▓▒░╝"},
	{"▁▂▃▅ {S} ▅▃▂▁", "▁▂▃▅ {S} ▅▃▂▁"},
	{"╔═╡ {S} ╞═════╗", "╚═╡ {S} ╞═════╝"},
	{"░▒▓█ {S} █▓▒░", "░▒▓█ {S} █▓▒░"},
	{"╔▬▬▬ {S} ▬▬▬╗", "╚▬▬▬ {S} ▬▬▬╝"},
	{"✩░▒▓ {S} ▓▒░✩", "✩░▒▓ {S} ▓▒░✩"},
	{"╔◇◆◇ {S} ◇◆◇╗", "╚◇◆◇ {S} ◇◆◇╝"},
	{"❰❰❰❰ {S} ❱❱❱❱", "❰❰❰❰ {S} ❱❱❱❱"},
	{"╔╌╌╌╌ {S} ╌╌╌╌╗", "╚╌╌╌╌ {S} ╌╌╌╌╝"},
	{"▚▞▚▞ {S} ▞▚▞▚", "▚▞▚▞ {S} ▞▚▞▚"},
	{"╔═══╗{S}╔═══╗", "╚═══╝{S}╚═══╝"},
	{"••••• {S} •••••", "••••• {S} •••••"},
	{"█▀▀█ {S} █▀▀█", "█▄▄█ {S} █▄▄█"},
	{"╔♦♦♦ {S} ♦♦♦╗", "╚♦♦♦ {S} ♦♦♦╝"},
	{"░▀▄ {S} ▄▀░", "░▀▄ {S} ▄▀░"},
	{"╭══╮ {S} ╭══╮", "╰══╯ {S} ╰══╯"},
	{"▓▓▒▒ {S} ▒▒▓▓", "▓▓▒▒ {S} ▒▒▓▓"},
	{"⋘⋘ {S} ⋙⋙", "⋘⋘ {S} ⋙⋙"},
	{"╔≺≺ {S} ≻≻════╗", "╚≺≺ {S} ≻≻════╝"},
	{"✺✹✸ {S} ✸✹✺", "✺✹✸ {S} ✸✹✺"},
	{"╔─━─━ {S} ━─━─╗", "╚─━─━ {S} ━─━─╝"},
	{"◜◝◞◟ {S} ◟◞◝◜", "◜◝◞◟ {S} ◟◞◝◜"},
	{"╔═══ ≪• {S} •≫ ═══╗", "╚═══ ≪• {S} •≫ ═══╝"},
	{"▰▱▰▱ {S} ▱▰▱▰", "▰▱▰▱ {S} ▱▰▱▰"},
	{"⚡⚡ {S} ⚡⚡", "⚡⚡ {S} ⚡⚡"},
	{"╔▣▣▣ {S} ▣▣▣╗", "╚▣▣▣ {S} ▣▣▣╝"},
	{"✜✛✜✛ {S} ✛✜✛✜", "✜✛✜✛ {S} ✛✜✛✜"},
	{"❰══❱ {S} ❰══❱", "❰══❱ {S} ❰══❱"},
	{"╔◆◇◆◇ {S} ◇◆◇◆╗", "╚◆◇◆◇ {S} ◇◆◇◆╝"},
	{"◈◈◈◈ {S} ◈◈◈◈", "◈◈◈◈ {S} ◈◈◈◈"},
}

// styleRows are the 20 row-decoration templates. {S} = the style symbol.
var styleRows = []struct{ L, R string }{
	{"❃ ", " ❃"},
	{"✦ ▸ ", ""},
	{"【{S}】 ", ""},
	{"║ {S} ║ ", ""},
	{"⟦ {S} ⟧ ", ""},
	{"✦ ", " ✦"},
	{"◈ ", " ◈"},
	{"▸ ", " ◂"},
	{"|{S}| ", ""},
	{"✧ ", " ✧"},
	{"◆ ", " ◆"},
	{"❰{S}❱ ", ""},
	{"•{S}• ", ""},
	{"┃{S}┃ ", ""},
	{"❯ ", " ❮"},
	{"≡ ", " ≡"},
	{"✩ ", " ✩"},
	{"★ ", " ★"},
	{"◇ ", " ◇"},
	{"▹ ", " ◃"},
}

// styleNames are the 1000 design labels (50 adjectives x 20 nouns, all unique).
var styleNames = []string{
	"ROYAL CROWN", "ROYAL DIAMOND", "ROYAL STAR", "ROYAL RING", "ROYAL GEM", "ROYAL EYE", "ROYAL SPARK", "ROYAL SCROLL", "ROYAL BLOOM", "ROYAL SEAL", "ROYAL GRID", "ROYAL SHIELD",
	"ROYAL TRIAD", "ROYAL SHARD", "ROYAL WHISPER", "ROYAL MARK", "ROYAL FLAME", "ROYAL WAVE", "ROYAL TIDE", "ROYAL VORTEX", "NEON CROWN", "NEON DIAMOND", "NEON STAR", "NEON RING",
	"NEON GEM", "NEON EYE", "NEON SPARK", "NEON SCROLL", "NEON BLOOM", "NEON SEAL", "NEON GRID", "NEON SHIELD", "NEON TRIAD", "NEON SHARD", "NEON WHISPER", "NEON MARK",
	"NEON FLAME", "NEON WAVE", "NEON TIDE", "NEON VORTEX", "GOLDEN CROWN", "GOLDEN DIAMOND", "GOLDEN STAR", "GOLDEN RING", "GOLDEN GEM", "GOLDEN EYE", "GOLDEN SPARK", "GOLDEN SCROLL",
	"GOLDEN BLOOM", "GOLDEN SEAL", "GOLDEN GRID", "GOLDEN SHIELD", "GOLDEN TRIAD", "GOLDEN SHARD", "GOLDEN WHISPER", "GOLDEN MARK", "GOLDEN FLAME", "GOLDEN WAVE", "GOLDEN TIDE", "GOLDEN VORTEX",
	"MIDNIGHT CROWN", "MIDNIGHT DIAMOND", "MIDNIGHT STAR", "MIDNIGHT RING", "MIDNIGHT GEM", "MIDNIGHT EYE", "MIDNIGHT SPARK", "MIDNIGHT SCROLL", "MIDNIGHT BLOOM", "MIDNIGHT SEAL", "MIDNIGHT GRID", "MIDNIGHT SHIELD",
	"MIDNIGHT TRIAD", "MIDNIGHT SHARD", "MIDNIGHT WHISPER", "MIDNIGHT MARK", "MIDNIGHT FLAME", "MIDNIGHT WAVE", "MIDNIGHT TIDE", "MIDNIGHT VORTEX", "COSMIC CROWN", "COSMIC DIAMOND", "COSMIC STAR", "COSMIC RING",
	"COSMIC GEM", "COSMIC EYE", "COSMIC SPARK", "COSMIC SCROLL", "COSMIC BLOOM", "COSMIC SEAL", "COSMIC GRID", "COSMIC SHIELD", "COSMIC TRIAD", "COSMIC SHARD", "COSMIC WHISPER", "COSMIC MARK",
	"COSMIC FLAME", "COSMIC WAVE", "COSMIC TIDE", "COSMIC VORTEX", "CRYSTAL CROWN", "CRYSTAL DIAMOND", "CRYSTAL STAR", "CRYSTAL RING", "CRYSTAL GEM", "CRYSTAL EYE", "CRYSTAL SPARK", "CRYSTAL SCROLL",
	"CRYSTAL BLOOM", "CRYSTAL SEAL", "CRYSTAL GRID", "CRYSTAL SHIELD", "CRYSTAL TRIAD", "CRYSTAL SHARD", "CRYSTAL WHISPER", "CRYSTAL MARK", "CRYSTAL FLAME", "CRYSTAL WAVE", "CRYSTAL TIDE", "CRYSTAL VORTEX",
	"SHADOW CROWN", "SHADOW DIAMOND", "SHADOW STAR", "SHADOW RING", "SHADOW GEM", "SHADOW EYE", "SHADOW SPARK", "SHADOW SCROLL", "SHADOW BLOOM", "SHADOW SEAL", "SHADOW GRID", "SHADOW SHIELD",
	"SHADOW TRIAD", "SHADOW SHARD", "SHADOW WHISPER", "SHADOW MARK", "SHADOW FLAME", "SHADOW WAVE", "SHADOW TIDE", "SHADOW VORTEX", "IMPERIAL CROWN", "IMPERIAL DIAMOND", "IMPERIAL STAR", "IMPERIAL RING",
	"IMPERIAL GEM", "IMPERIAL EYE", "IMPERIAL SPARK", "IMPERIAL SCROLL", "IMPERIAL BLOOM", "IMPERIAL SEAL", "IMPERIAL GRID", "IMPERIAL SHIELD", "IMPERIAL TRIAD", "IMPERIAL SHARD", "IMPERIAL WHISPER", "IMPERIAL MARK",
	"IMPERIAL FLAME", "IMPERIAL WAVE", "IMPERIAL TIDE", "IMPERIAL VORTEX", "AURORA CROWN", "AURORA DIAMOND", "AURORA STAR", "AURORA RING", "AURORA GEM", "AURORA EYE", "AURORA SPARK", "AURORA SCROLL",
	"AURORA BLOOM", "AURORA SEAL", "AURORA GRID", "AURORA SHIELD", "AURORA TRIAD", "AURORA SHARD", "AURORA WHISPER", "AURORA MARK", "AURORA FLAME", "AURORA WAVE", "AURORA TIDE", "AURORA VORTEX",
	"FROST CROWN", "FROST DIAMOND", "FROST STAR", "FROST RING", "FROST GEM", "FROST EYE", "FROST SPARK", "FROST SCROLL", "FROST BLOOM", "FROST SEAL", "FROST GRID", "FROST SHIELD",
	"FROST TRIAD", "FROST SHARD", "FROST WHISPER", "FROST MARK", "FROST FLAME", "FROST WAVE", "FROST TIDE", "FROST VORTEX", "BLAZING CROWN", "BLAZING DIAMOND", "BLAZING STAR", "BLAZING RING",
	"BLAZING GEM", "BLAZING EYE", "BLAZING SPARK", "BLAZING SCROLL", "BLAZING BLOOM", "BLAZING SEAL", "BLAZING GRID", "BLAZING SHIELD", "BLAZING TRIAD", "BLAZING SHARD", "BLAZING WHISPER", "BLAZING MARK",
	"BLAZING FLAME", "BLAZING WAVE", "BLAZING TIDE", "BLAZING VORTEX", "VELVET CROWN", "VELVET DIAMOND", "VELVET STAR", "VELVET RING", "VELVET GEM", "VELVET EYE", "VELVET SPARK", "VELVET SCROLL",
	"VELVET BLOOM", "VELVET SEAL", "VELVET GRID", "VELVET SHIELD", "VELVET TRIAD", "VELVET SHARD", "VELVET WHISPER", "VELVET MARK", "VELVET FLAME", "VELVET WAVE", "VELVET TIDE", "VELVET VORTEX",
	"OBSIDIAN CROWN", "OBSIDIAN DIAMOND", "OBSIDIAN STAR", "OBSIDIAN RING", "OBSIDIAN GEM", "OBSIDIAN EYE", "OBSIDIAN SPARK", "OBSIDIAN SCROLL", "OBSIDIAN BLOOM", "OBSIDIAN SEAL", "OBSIDIAN GRID", "OBSIDIAN SHIELD",
	"OBSIDIAN TRIAD", "OBSIDIAN SHARD", "OBSIDIAN WHISPER", "OBSIDIAN MARK", "OBSIDIAN FLAME", "OBSIDIAN WAVE", "OBSIDIAN TIDE", "OBSIDIAN VORTEX", "SILVER CROWN", "SILVER DIAMOND", "SILVER STAR", "SILVER RING",
	"SILVER GEM", "SILVER EYE", "SILVER SPARK", "SILVER SCROLL", "SILVER BLOOM", "SILVER SEAL", "SILVER GRID", "SILVER SHIELD", "SILVER TRIAD", "SILVER SHARD", "SILVER WHISPER", "SILVER MARK",
	"SILVER FLAME", "SILVER WAVE", "SILVER TIDE", "SILVER VORTEX", "SUNSET CROWN", "SUNSET DIAMOND", "SUNSET STAR", "SUNSET RING", "SUNSET GEM", "SUNSET EYE", "SUNSET SPARK", "SUNSET SCROLL",
	"SUNSET BLOOM", "SUNSET SEAL", "SUNSET GRID", "SUNSET SHIELD", "SUNSET TRIAD", "SUNSET SHARD", "SUNSET WHISPER", "SUNSET MARK", "SUNSET FLAME", "SUNSET WAVE", "SUNSET TIDE", "SUNSET VORTEX",
	"EMERALD CROWN", "EMERALD DIAMOND", "EMERALD STAR", "EMERALD RING", "EMERALD GEM", "EMERALD EYE", "EMERALD SPARK", "EMERALD SCROLL", "EMERALD BLOOM", "EMERALD SEAL", "EMERALD GRID", "EMERALD SHIELD",
	"EMERALD TRIAD", "EMERALD SHARD", "EMERALD WHISPER", "EMERALD MARK", "EMERALD FLAME", "EMERALD WAVE", "EMERALD TIDE", "EMERALD VORTEX", "SAKURA CROWN", "SAKURA DIAMOND", "SAKURA STAR", "SAKURA RING",
	"SAKURA GEM", "SAKURA EYE", "SAKURA SPARK", "SAKURA SCROLL", "SAKURA BLOOM", "SAKURA SEAL", "SAKURA GRID", "SAKURA SHIELD", "SAKURA TRIAD", "SAKURA SHARD", "SAKURA WHISPER", "SAKURA MARK",
	"SAKURA FLAME", "SAKURA WAVE", "SAKURA TIDE", "SAKURA VORTEX", "LUNAR CROWN", "LUNAR DIAMOND", "LUNAR STAR", "LUNAR RING", "LUNAR GEM", "LUNAR EYE", "LUNAR SPARK", "LUNAR SCROLL",
	"LUNAR BLOOM", "LUNAR SEAL", "LUNAR GRID", "LUNAR SHIELD", "LUNAR TRIAD", "LUNAR SHARD", "LUNAR WHISPER", "LUNAR MARK", "LUNAR FLAME", "LUNAR WAVE", "LUNAR TIDE", "LUNAR VORTEX",
	"SOLAR CROWN", "SOLAR DIAMOND", "SOLAR STAR", "SOLAR RING", "SOLAR GEM", "SOLAR EYE", "SOLAR SPARK", "SOLAR SCROLL", "SOLAR BLOOM", "SOLAR SEAL", "SOLAR GRID", "SOLAR SHIELD",
	"SOLAR TRIAD", "SOLAR SHARD", "SOLAR WHISPER", "SOLAR MARK", "SOLAR FLAME", "SOLAR WAVE", "SOLAR TIDE", "SOLAR VORTEX", "PHANTOM CROWN", "PHANTOM DIAMOND", "PHANTOM STAR", "PHANTOM RING",
	"PHANTOM GEM", "PHANTOM EYE", "PHANTOM SPARK", "PHANTOM SCROLL", "PHANTOM BLOOM", "PHANTOM SEAL", "PHANTOM GRID", "PHANTOM SHIELD", "PHANTOM TRIAD", "PHANTOM SHARD", "PHANTOM WHISPER", "PHANTOM MARK",
	"PHANTOM FLAME", "PHANTOM WAVE", "PHANTOM TIDE", "PHANTOM VORTEX", "IRON CROWN", "IRON DIAMOND", "IRON STAR", "IRON RING", "IRON GEM", "IRON EYE", "IRON SPARK", "IRON SCROLL",
	"IRON BLOOM", "IRON SEAL", "IRON GRID", "IRON SHIELD", "IRON TRIAD", "IRON SHARD", "IRON WHISPER", "IRON MARK", "IRON FLAME", "IRON WAVE", "IRON TIDE", "IRON VORTEX",
	"SAPPHIRE CROWN", "SAPPHIRE DIAMOND", "SAPPHIRE STAR", "SAPPHIRE RING", "SAPPHIRE GEM", "SAPPHIRE EYE", "SAPPHIRE SPARK", "SAPPHIRE SCROLL", "SAPPHIRE BLOOM", "SAPPHIRE SEAL", "SAPPHIRE GRID", "SAPPHIRE SHIELD",
	"SAPPHIRE TRIAD", "SAPPHIRE SHARD", "SAPPHIRE WHISPER", "SAPPHIRE MARK", "SAPPHIRE FLAME", "SAPPHIRE WAVE", "SAPPHIRE TIDE", "SAPPHIRE VORTEX", "AMBER CROWN", "AMBER DIAMOND", "AMBER STAR", "AMBER RING",
	"AMBER GEM", "AMBER EYE", "AMBER SPARK", "AMBER SCROLL", "AMBER BLOOM", "AMBER SEAL", "AMBER GRID", "AMBER SHIELD", "AMBER TRIAD", "AMBER SHARD", "AMBER WHISPER", "AMBER MARK",
	"AMBER FLAME", "AMBER WAVE", "AMBER TIDE", "AMBER VORTEX", "CORAL CROWN", "CORAL DIAMOND", "CORAL STAR", "CORAL RING", "CORAL GEM", "CORAL EYE", "CORAL SPARK", "CORAL SCROLL",
	"CORAL BLOOM", "CORAL SEAL", "CORAL GRID", "CORAL SHIELD", "CORAL TRIAD", "CORAL SHARD", "CORAL WHISPER", "CORAL MARK", "CORAL FLAME", "CORAL WAVE", "CORAL TIDE", "CORAL VORTEX",
	"JADE CROWN", "JADE DIAMOND", "JADE STAR", "JADE RING", "JADE GEM", "JADE EYE", "JADE SPARK", "JADE SCROLL", "JADE BLOOM", "JADE SEAL", "JADE GRID", "JADE SHIELD",
	"JADE TRIAD", "JADE SHARD", "JADE WHISPER", "JADE MARK", "JADE FLAME", "JADE WAVE", "JADE TIDE", "JADE VORTEX", "ONYX CROWN", "ONYX DIAMOND", "ONYX STAR", "ONYX RING",
	"ONYX GEM", "ONYX EYE", "ONYX SPARK", "ONYX SCROLL", "ONYX BLOOM", "ONYX SEAL", "ONYX GRID", "ONYX SHIELD", "ONYX TRIAD", "ONYX SHARD", "ONYX WHISPER", "ONYX MARK",
	"ONYX FLAME", "ONYX WAVE", "ONYX TIDE", "ONYX VORTEX", "RUBY CROWN", "RUBY DIAMOND", "RUBY STAR", "RUBY RING", "RUBY GEM", "RUBY EYE", "RUBY SPARK", "RUBY SCROLL",
	"RUBY BLOOM", "RUBY SEAL", "RUBY GRID", "RUBY SHIELD", "RUBY TRIAD", "RUBY SHARD", "RUBY WHISPER", "RUBY MARK", "RUBY FLAME", "RUBY WAVE", "RUBY TIDE", "RUBY VORTEX",
	"TOPAZ CROWN", "TOPAZ DIAMOND", "TOPAZ STAR", "TOPAZ RING", "TOPAZ GEM", "TOPAZ EYE", "TOPAZ SPARK", "TOPAZ SCROLL", "TOPAZ BLOOM", "TOPAZ SEAL", "TOPAZ GRID", "TOPAZ SHIELD",
	"TOPAZ TRIAD", "TOPAZ SHARD", "TOPAZ WHISPER", "TOPAZ MARK", "TOPAZ FLAME", "TOPAZ WAVE", "TOPAZ TIDE", "TOPAZ VORTEX", "OPAL CROWN", "OPAL DIAMOND", "OPAL STAR", "OPAL RING",
	"OPAL GEM", "OPAL EYE", "OPAL SPARK", "OPAL SCROLL", "OPAL BLOOM", "OPAL SEAL", "OPAL GRID", "OPAL SHIELD", "OPAL TRIAD", "OPAL SHARD", "OPAL WHISPER", "OPAL MARK",
	"OPAL FLAME", "OPAL WAVE", "OPAL TIDE", "OPAL VORTEX", "PEARL CROWN", "PEARL DIAMOND", "PEARL STAR", "PEARL RING", "PEARL GEM", "PEARL EYE", "PEARL SPARK", "PEARL SCROLL",
	"PEARL BLOOM", "PEARL SEAL", "PEARL GRID", "PEARL SHIELD", "PEARL TRIAD", "PEARL SHARD", "PEARL WHISPER", "PEARL MARK", "PEARL FLAME", "PEARL WAVE", "PEARL TIDE", "PEARL VORTEX",
	"VIOLET CROWN", "VIOLET DIAMOND", "VIOLET STAR", "VIOLET RING", "VIOLET GEM", "VIOLET EYE", "VIOLET SPARK", "VIOLET SCROLL", "VIOLET BLOOM", "VIOLET SEAL", "VIOLET GRID", "VIOLET SHIELD",
	"VIOLET TRIAD", "VIOLET SHARD", "VIOLET WHISPER", "VIOLET MARK", "VIOLET FLAME", "VIOLET WAVE", "VIOLET TIDE", "VIOLET VORTEX", "CRIMSON CROWN", "CRIMSON DIAMOND", "CRIMSON STAR", "CRIMSON RING",
	"CRIMSON GEM", "CRIMSON EYE", "CRIMSON SPARK", "CRIMSON SCROLL", "CRIMSON BLOOM", "CRIMSON SEAL", "CRIMSON GRID", "CRIMSON SHIELD", "CRIMSON TRIAD", "CRIMSON SHARD", "CRIMSON WHISPER", "CRIMSON MARK",
	"CRIMSON FLAME", "CRIMSON WAVE", "CRIMSON TIDE", "CRIMSON VORTEX", "INDIGO CROWN", "INDIGO DIAMOND", "INDIGO STAR", "INDIGO RING", "INDIGO GEM", "INDIGO EYE", "INDIGO SPARK", "INDIGO SCROLL",
	"INDIGO BLOOM", "INDIGO SEAL", "INDIGO GRID", "INDIGO SHIELD", "INDIGO TRIAD", "INDIGO SHARD", "INDIGO WHISPER", "INDIGO MARK", "INDIGO FLAME", "INDIGO WAVE", "INDIGO TIDE", "INDIGO VORTEX",
	"TURQUOISE CROWN", "TURQUOISE DIAMOND", "TURQUOISE STAR", "TURQUOISE RING", "TURQUOISE GEM", "TURQUOISE EYE", "TURQUOISE SPARK", "TURQUOISE SCROLL", "TURQUOISE BLOOM", "TURQUOISE SEAL", "TURQUOISE GRID", "TURQUOISE SHIELD",
	"TURQUOISE TRIAD", "TURQUOISE SHARD", "TURQUOISE WHISPER", "TURQUOISE MARK", "TURQUOISE FLAME", "TURQUOISE WAVE", "TURQUOISE TIDE", "TURQUOISE VORTEX", "MAGENTA CROWN", "MAGENTA DIAMOND", "MAGENTA STAR", "MAGENTA RING",
	"MAGENTA GEM", "MAGENTA EYE", "MAGENTA SPARK", "MAGENTA SCROLL", "MAGENTA BLOOM", "MAGENTA SEAL", "MAGENTA GRID", "MAGENTA SHIELD", "MAGENTA TRIAD", "MAGENTA SHARD", "MAGENTA WHISPER", "MAGENTA MARK",
	"MAGENTA FLAME", "MAGENTA WAVE", "MAGENTA TIDE", "MAGENTA VORTEX", "AZURE CROWN", "AZURE DIAMOND", "AZURE STAR", "AZURE RING", "AZURE GEM", "AZURE EYE", "AZURE SPARK", "AZURE SCROLL",
	"AZURE BLOOM", "AZURE SEAL", "AZURE GRID", "AZURE SHIELD", "AZURE TRIAD", "AZURE SHARD", "AZURE WHISPER", "AZURE MARK", "AZURE FLAME", "AZURE WAVE", "AZURE TIDE", "AZURE VORTEX",
	"BRONZE CROWN", "BRONZE DIAMOND", "BRONZE STAR", "BRONZE RING", "BRONZE GEM", "BRONZE EYE", "BRONZE SPARK", "BRONZE SCROLL", "BRONZE BLOOM", "BRONZE SEAL", "BRONZE GRID", "BRONZE SHIELD",
	"BRONZE TRIAD", "BRONZE SHARD", "BRONZE WHISPER", "BRONZE MARK", "BRONZE FLAME", "BRONZE WAVE", "BRONZE TIDE", "BRONZE VORTEX", "COPPER CROWN", "COPPER DIAMOND", "COPPER STAR", "COPPER RING",
	"COPPER GEM", "COPPER EYE", "COPPER SPARK", "COPPER SCROLL", "COPPER BLOOM", "COPPER SEAL", "COPPER GRID", "COPPER SHIELD", "COPPER TRIAD", "COPPER SHARD", "COPPER WHISPER", "COPPER MARK",
	"COPPER FLAME", "COPPER WAVE", "COPPER TIDE", "COPPER VORTEX", "PLATINUM CROWN", "PLATINUM DIAMOND", "PLATINUM STAR", "PLATINUM RING", "PLATINUM GEM", "PLATINUM EYE", "PLATINUM SPARK", "PLATINUM SCROLL",
	"PLATINUM BLOOM", "PLATINUM SEAL", "PLATINUM GRID", "PLATINUM SHIELD", "PLATINUM TRIAD", "PLATINUM SHARD", "PLATINUM WHISPER", "PLATINUM MARK", "PLATINUM FLAME", "PLATINUM WAVE", "PLATINUM TIDE", "PLATINUM VORTEX",
	"TITAN CROWN", "TITAN DIAMOND", "TITAN STAR", "TITAN RING", "TITAN GEM", "TITAN EYE", "TITAN SPARK", "TITAN SCROLL", "TITAN BLOOM", "TITAN SEAL", "TITAN GRID", "TITAN SHIELD",
	"TITAN TRIAD", "TITAN SHARD", "TITAN WHISPER", "TITAN MARK", "TITAN FLAME", "TITAN WAVE", "TITAN TIDE", "TITAN VORTEX", "MYSTIC CROWN", "MYSTIC DIAMOND", "MYSTIC STAR", "MYSTIC RING",
	"MYSTIC GEM", "MYSTIC EYE", "MYSTIC SPARK", "MYSTIC SCROLL", "MYSTIC BLOOM", "MYSTIC SEAL", "MYSTIC GRID", "MYSTIC SHIELD", "MYSTIC TRIAD", "MYSTIC SHARD", "MYSTIC WHISPER", "MYSTIC MARK",
	"MYSTIC FLAME", "MYSTIC WAVE", "MYSTIC TIDE", "MYSTIC VORTEX", "ANCIENT CROWN", "ANCIENT DIAMOND", "ANCIENT STAR", "ANCIENT RING", "ANCIENT GEM", "ANCIENT EYE", "ANCIENT SPARK", "ANCIENT SCROLL",
	"ANCIENT BLOOM", "ANCIENT SEAL", "ANCIENT GRID", "ANCIENT SHIELD", "ANCIENT TRIAD", "ANCIENT SHARD", "ANCIENT WHISPER", "ANCIENT MARK", "ANCIENT FLAME", "ANCIENT WAVE", "ANCIENT TIDE", "ANCIENT VORTEX",
	"CELESTIAL CROWN", "CELESTIAL DIAMOND", "CELESTIAL STAR", "CELESTIAL RING", "CELESTIAL GEM", "CELESTIAL EYE", "CELESTIAL SPARK", "CELESTIAL SCROLL", "CELESTIAL BLOOM", "CELESTIAL SEAL", "CELESTIAL GRID", "CELESTIAL SHIELD",
	"CELESTIAL TRIAD", "CELESTIAL SHARD", "CELESTIAL WHISPER", "CELESTIAL MARK", "CELESTIAL FLAME", "CELESTIAL WAVE", "CELESTIAL TIDE", "CELESTIAL VORTEX", "ETHEREAL CROWN", "ETHEREAL DIAMOND", "ETHEREAL STAR", "ETHEREAL RING",
	"ETHEREAL GEM", "ETHEREAL EYE", "ETHEREAL SPARK", "ETHEREAL SCROLL", "ETHEREAL BLOOM", "ETHEREAL SEAL", "ETHEREAL GRID", "ETHEREAL SHIELD", "ETHEREAL TRIAD", "ETHEREAL SHARD", "ETHEREAL WHISPER", "ETHEREAL MARK",
	"ETHEREAL FLAME", "ETHEREAL WAVE", "ETHEREAL TIDE", "ETHEREAL VORTEX", "FROZEN CROWN", "FROZEN DIAMOND", "FROZEN STAR", "FROZEN RING", "FROZEN GEM", "FROZEN EYE", "FROZEN SPARK", "FROZEN SCROLL",
	"FROZEN BLOOM", "FROZEN SEAL", "FROZEN GRID", "FROZEN SHIELD", "FROZEN TRIAD", "FROZEN SHARD", "FROZEN WHISPER", "FROZEN MARK", "FROZEN FLAME", "FROZEN WAVE", "FROZEN TIDE", "FROZEN VORTEX",
	"BURNING CROWN", "BURNING DIAMOND", "BURNING STAR", "BURNING RING", "BURNING GEM", "BURNING EYE", "BURNING SPARK", "BURNING SCROLL", "BURNING BLOOM", "BURNING SEAL", "BURNING GRID", "BURNING SHIELD",
	"BURNING TRIAD", "BURNING SHARD", "BURNING WHISPER", "BURNING MARK", "BURNING FLAME", "BURNING WAVE", "BURNING TIDE", "BURNING VORTEX", "SILENT CROWN", "SILENT DIAMOND", "SILENT STAR", "SILENT RING",
	"SILENT GEM", "SILENT EYE", "SILENT SPARK", "SILENT SCROLL", "SILENT BLOOM", "SILENT SEAL", "SILENT GRID", "SILENT SHIELD", "SILENT TRIAD", "SILENT SHARD", "SILENT WHISPER", "SILENT MARK",
	"SILENT FLAME", "SILENT WAVE", "SILENT TIDE", "SILENT VORTEX", "WILD CROWN", "WILD DIAMOND", "WILD STAR", "WILD RING", "WILD GEM", "WILD EYE", "WILD SPARK", "WILD SCROLL",
	"WILD BLOOM", "WILD SEAL", "WILD GRID", "WILD SHIELD", "WILD TRIAD", "WILD SHARD", "WILD WHISPER", "WILD MARK", "WILD FLAME", "WILD WAVE", "WILD TIDE", "WILD VORTEX",
	"NOBLE CROWN", "NOBLE DIAMOND", "NOBLE STAR", "NOBLE RING", "NOBLE GEM", "NOBLE EYE", "NOBLE SPARK", "NOBLE SCROLL", "NOBLE BLOOM", "NOBLE SEAL", "NOBLE GRID", "NOBLE SHIELD",
	"NOBLE TRIAD", "NOBLE SHARD", "NOBLE WHISPER", "NOBLE MARK", "NOBLE FLAME", "NOBLE WAVE", "NOBLE TIDE", "NOBLE VORTEX", "DARK CROWN", "DARK DIAMOND", "DARK STAR", "DARK RING",
	"DARK GEM", "DARK EYE", "DARK SPARK", "DARK SCROLL", "DARK BLOOM", "DARK SEAL", "DARK GRID", "DARK SHIELD", "DARK TRIAD", "DARK SHARD", "DARK WHISPER", "DARK MARK",
	"DARK FLAME", "DARK WAVE", "DARK TIDE", "DARK VORTEX",
}
